import type { FlowerSurfaceCopy } from '../../../../internal/flower_ui/src/copy';
import { localizedFlowerProviderModelNote } from '../../../../internal/flower_ui/src/settings/providerModelNotes';
import { localizedFlowerProviderTypeLabels } from '../../../../internal/flower_ui/src/settings/providerTypeLabels';
import type { DesktopI18n } from '../../shared/i18n';

type CopyKey = Parameters<DesktopI18n['t']>[0];

function t(i18n: DesktopI18n, key: CopyKey, params?: Parameters<DesktopI18n['t']>[1]): string {
  return i18n.t(key, params);
}

export function createDesktopFlowerSurfaceCopy(i18n: DesktopI18n): FlowerSurfaceCopy {
  const k = (suffix: string) => `flowerSurface.${suffix}` as CopyKey;
  return {
    chat: {
      loadingSettings: t(i18n, k('chat.loadingSettings')),
      configureProviderBeforeChat: t(i18n, k('chat.configureProviderBeforeChat')),
      enterMessageBeforeSending: t(i18n, k('chat.enterMessageBeforeSending')),
      titleFallback: t(i18n, k('chat.titleFallback')),
      ready: t(i18n, k('chat.ready')),
      setupNeeded: t(i18n, k('chat.setupNeeded')),
      settingsLabel: t(i18n, k('chat.settingsLabel')),
      needsProviderNotice: t(i18n, k('chat.needsProviderNotice')),
      openSettings: t(i18n, k('chat.openSettings')),
      placeholder: t(i18n, k('chat.placeholder')),
      fromHost: (host) => t(i18n, k('chat.fromHost'), { host }),
      handlerSelectionLabel: t(i18n, k('chat.handlerSelectionLabel')),
      handlerResolving: t(i18n, k('chat.handlerResolving')),
      handlerUnavailable: t(i18n, k('chat.handlerUnavailable')),
      handlerRetry: t(i18n, k('chat.handlerRetry')),
      send: t(i18n, k('chat.send')),
      runErrorTitle: t(i18n, k('chat.runErrorTitle')),
      messageErrorTitle: t(i18n, k('chat.messageErrorTitle')),
      messageErrorFallback: t(i18n, k('chat.messageErrorFallback')),
      loadErrorTitle: t(i18n, k('chat.loadErrorTitle')),
      threadLoadErrorTitle: t(i18n, k('chat.threadLoadErrorTitle')),
      threadLoading: t(i18n, k('chat.threadLoading')),
      composerErrorTitle: t(i18n, k('chat.composerErrorTitle')),
      toolActivityLabel: t(i18n, k('chat.toolActivityLabel')),
      toolStatuses: {
        pending: t(i18n, k('chat.toolStatusPending')),
        running: t(i18n, k('chat.toolStatusRunning')),
        waiting: t(i18n, k('chat.toolStatusWaiting')),
        success: t(i18n, k('chat.toolStatusSuccess')),
        error: t(i18n, k('chat.toolStatusError')),
        canceled: t(i18n, k('chat.toolStatusCanceled')),
      },
      toolApprovalRequired: t(i18n, k('chat.toolApprovalRequired')),
      toolApprovalState: (state) => t(i18n, k('chat.toolApprovalState'), { state }),
      conversationsAria: t(i18n, k('chat.conversationsAria')),
      resizeConversationsLabel: t(i18n, k('chat.resizeConversationsLabel')),
      entryLabel: t(i18n, k('chat.entryLabel')),
      newChat: t(i18n, k('chat.newChat')),
    },
    threadList: {
      title: t(i18n, k('threadList.title')),
      description: t(i18n, k('threadList.description')),
      refreshLabel: t(i18n, k('threadList.refreshLabel')),
      searchPlaceholder: t(i18n, k('threadList.searchPlaceholder')),
      empty: t(i18n, k('threadList.empty')),
      untitled: t(i18n, k('threadList.untitled')),
      working: t(i18n, k('threadList.working')),
      deleteLabel: (title) => t(i18n, k('threadList.deleteLabel'), { title }),
      now: t(i18n, k('threadList.now')),
      minutes: (count) => t(i18n, k('threadList.minutes'), { count }),
      hours: (count) => t(i18n, k('threadList.hours'), { count }),
      days: (count) => t(i18n, k('threadList.days'), { count }),
      statuses: {
        idle: t(i18n, k('threadList.statusIdle')),
        running: t(i18n, k('threadList.statusRunning')),
        waiting_user: t(i18n, k('threadList.statusWaitingUser')),
        waiting_approval: t(i18n, k('threadList.statusWaitingApproval')),
        failed: t(i18n, k('threadList.statusFailed')),
        success: t(i18n, k('threadList.statusSuccess')),
        read_only: t(i18n, k('threadList.statusReadOnly')),
      },
      groups: {
        today: t(i18n, k('threadList.groupToday')),
        yesterday: t(i18n, k('threadList.groupYesterday')),
        this_week: t(i18n, k('threadList.groupThisWeek')),
        older: t(i18n, k('threadList.groupOlder')),
      },
    },
    emptyState: {
      title: t(i18n, k('emptyState.title')),
      description: t(i18n, k('emptyState.description')),
      suggestions: [
        {
          title: t(i18n, k('emptyState.reviewTitle')),
          description: t(i18n, k('emptyState.reviewDescription')),
          prompt: t(i18n, k('emptyState.reviewPrompt')),
        },
        {
          title: t(i18n, k('emptyState.transferTitle')),
          description: t(i18n, k('emptyState.transferDescription')),
          prompt: t(i18n, k('emptyState.transferPrompt')),
        },
        {
          title: t(i18n, k('emptyState.explainTitle')),
          description: t(i18n, k('emptyState.explainDescription')),
          prompt: t(i18n, k('emptyState.explainPrompt')),
        },
        {
          title: t(i18n, k('emptyState.workflowTitle')),
          description: t(i18n, k('emptyState.workflowDescription')),
          prompt: t(i18n, k('emptyState.workflowPrompt')),
        },
      ],
      sendKeyLabel: t(i18n, k('emptyState.sendKeyLabel')),
      newLineKeyLabel: t(i18n, k('emptyState.newLineKeyLabel')),
    },
    settings: createDesktopFlowerSettingsCopy(i18n),
  };
}

function createDesktopFlowerSettingsCopy(i18n: DesktopI18n): FlowerSurfaceCopy['settings'] {
  const k = (suffix: string) => `flowerSurface.settings.${suffix}` as CopyKey;
  return {
    title: t(i18n, k('title')),
    backToChat: t(i18n, k('backToChat')),
    description: t(i18n, k('description')),
    active: t(i18n, k('active')),
    disabled: t(i18n, k('disabled')),
    enable: t(i18n, k('enable')),
    setup: t(i18n, k('setup')),
    disable: t(i18n, k('disable')),
    disabledNotice: t(i18n, k('disabledNotice')),
    currentModel: t(i18n, k('currentModel')),
    noModelSelected: t(i18n, k('noModelSelected')),
    text: t(i18n, k('text')),
    imageInput: t(i18n, k('imageInput')),
    selectModelPlaceholder: t(i18n, k('selectModelPlaceholder')),
    userApprovalTitle: t(i18n, k('userApprovalTitle')),
    userApprovalDescription: t(i18n, k('userApprovalDescription')),
    on: t(i18n, k('on')),
    off: t(i18n, k('off')),
    dangerousCommandsTitle: t(i18n, k('dangerousCommandsTitle')),
    dangerousCommandsDescription: t(i18n, k('dangerousCommandsDescription')),
    blocked: t(i18n, k('blocked')),
    allowed: t(i18n, k('allowed')),
    providersTitle: t(i18n, k('providersTitle')),
    providersDescription: t(i18n, k('providersDescription')),
    addProvider: t(i18n, k('addProvider')),
    noProviders: t(i18n, k('noProviders')),
    defaultProvider: t(i18n, k('defaultProvider')),
    editProvider: t(i18n, k('editProvider')),
    removeProvider: t(i18n, k('removeProvider')),
    apiKey: t(i18n, k('apiKey')),
    ready: t(i18n, k('ready')),
    needsKey: t(i18n, k('needsKey')),
    models: t(i18n, k('models')),
    web: t(i18n, k('web')),
    vision: t(i18n, k('vision')),
    terminalLimitsTitle: t(i18n, k('terminalLimitsTitle')),
    terminalLimitsDescription: t(i18n, k('terminalLimitsDescription')),
    defaultTimeout: t(i18n, k('defaultTimeout')),
    maximumTimeout: t(i18n, k('maximumTimeout')),
    dangerousBlockingOff: t(i18n, k('dangerousBlockingOff')),
    webSearchNotSupported: t(i18n, k('webSearchNotSupported')),
    webSearchDisabled: t(i18n, k('webSearchDisabled')),
    openAIBuiltIn: t(i18n, k('openAIBuiltIn')),
    braveSearch: t(i18n, k('braveSearch')),
    needsBraveKey: t(i18n, k('needsBraveKey')),
    providerTypeLabels: localizedFlowerProviderTypeLabels(i18n.locale),
    builtInWebSearch: {
      openai: t(i18n, k('openAIBuiltInWebSearch')),
      moonshot: t(i18n, k('kimiBuiltInWebSearch')),
      chatglm: t(i18n, k('glmBuiltInWebSearch')),
      deepseek: t(i18n, k('deepSeekBuiltInWebSearch')),
      qwen: t(i18n, k('qwenBuiltInWebSearch')),
    },
    autoSave: {
      saving: t(i18n, k('autoSaveSaving')),
      saveFailed: t(i18n, k('autoSaveFailed')),
      unsaved: t(i18n, k('autoSaveUnsaved')),
      saved: t(i18n, k('autoSaveSaved')),
      ready: t(i18n, k('autoSaveReady')),
    },
    validation: {
      providerIDRequired: t(i18n, k('providerIDRequired')),
      providerIDNoSlash: t(i18n, k('providerIDNoSlash')),
      duplicateProviderID: (providerID) => t(i18n, k('duplicateProviderID'), { providerID }),
      providerRequiresBaseURL: (providerName) => t(i18n, k('providerRequiresBaseURL'), { providerName }),
      providerInvalidBaseURL: (providerName) => t(i18n, k('providerInvalidBaseURL'), { providerName }),
      providerBaseURLProtocol: (providerName) => t(i18n, k('providerBaseURLProtocol'), { providerName }),
      providerNeedsModel: (providerName) => t(i18n, k('providerNeedsModel'), { providerName }),
      providerUnnamedModel: (providerName) => t(i18n, k('providerUnnamedModel'), { providerName }),
      modelNameNoSlash: t(i18n, k('modelNameNoSlash')),
      duplicateModel: (providerName, modelName) => t(i18n, k('duplicateModel'), { providerName, modelName }),
      modelNeedsContextWindow: (modelName) => t(i18n, k('modelNeedsContextWindow'), { modelName }),
      selectCurrentModel: t(i18n, k('selectCurrentModel')),
      currentModelUnavailable: (modelID) => t(i18n, k('currentModelUnavailable'), { modelID }),
      terminalTimeoutPositive: t(i18n, k('terminalTimeoutPositive')),
      terminalTimeoutOrder: t(i18n, k('terminalTimeoutOrder')),
    },
    dialog: createDesktopFlowerProviderDialogCopy(i18n),
  };
}

function createDesktopFlowerProviderDialogCopy(i18n: DesktopI18n): FlowerSurfaceCopy['settings']['dialog'] {
  const k = (suffix: string) => `flowerSurface.settings.${suffix}` as CopyKey;
  return {
    addTitle: t(i18n, k('dialogAddTitle')),
    editTitle: t(i18n, k('dialogEditTitle')),
    discard: t(i18n, k('dialogDiscard')),
    saveProvider: t(i18n, k('dialogSaveProvider')),
    providerRemoved: t(i18n, k('dialogProviderRemoved')),
    providerTypeTitle: t(i18n, k('dialogProviderTypeTitle')),
    providerTypeDescription: t(i18n, k('dialogProviderTypeDescription')),
    current: t(i18n, k('dialogCurrent')),
    collapse: t(i18n, k('dialogCollapse')),
    configure: t(i18n, k('dialogConfigure')),
    providerTypeLabels: localizedFlowerProviderTypeLabels(i18n.locale),
    providerTypeHints: {
      openai: t(i18n, k('dialogNativeConnection')),
      anthropic: t(i18n, k('dialogNativeConnection')),
      moonshot: t(i18n, k('dialogNativeConnection')),
      chatglm: t(i18n, k('dialogNativeConnection')),
      deepseek: t(i18n, k('dialogNativeConnection')),
      qwen: t(i18n, k('dialogNativeConnection')),
      openai_compatible: t(i18n, k('dialogCustomGateway')),
    },
    connectionTitle: t(i18n, k('dialogConnectionTitle')),
    connectionDescription: t(i18n, k('dialogConnectionDescription')),
    connectionName: t(i18n, k('dialogConnectionName')),
    apiKey: t(i18n, k('dialogAPIKey')),
    storedKeyKept: t(i18n, k('dialogStoredKeyKept')),
    requiredBeforeUse: t(i18n, k('dialogRequiredBeforeUse')),
    pasteAPIKey: t(i18n, k('dialogPasteAPIKey')),
    required: t(i18n, k('dialogRequired')),
    baseURL: t(i18n, k('dialogBaseURL')),
    webSearch: t(i18n, k('dialogWebSearch')),
    disabled: t(i18n, k('dialogDisabled')),
    openAIBuiltIn: t(i18n, k('dialogOpenAIBuiltIn')),
    braveSearch: t(i18n, k('dialogBraveSearch')),
    requiredForBraveSearch: t(i18n, k('dialogRequiredForBraveSearch')),
    braveAPIKey: t(i18n, k('dialogBraveAPIKey')),
    storedBraveKeyKept: t(i18n, k('dialogStoredBraveKeyKept')),
    pasteBraveAPIKey: t(i18n, k('dialogPasteBraveAPIKey')),
    keyReady: t(i18n, k('dialogKeyReady')),
    needsKey: t(i18n, k('dialogNeedsKey')),
    braveKeyReady: t(i18n, k('dialogBraveKeyReady')),
    needsBraveKey: t(i18n, k('dialogNeedsBraveKey')),
    builtInWebSearch: {
      openai: t(i18n, k('openAIBuiltInWebSearch')),
      moonshot: t(i18n, k('kimiBuiltInWebSearch')),
      chatglm: t(i18n, k('glmBuiltInWebSearch')),
      deepseek: t(i18n, k('deepSeekBuiltInWebSearch')),
      qwen: t(i18n, k('qwenBuiltInWebSearch')),
    },
    recommendedModelsTitle: t(i18n, k('dialogRecommendedModelsTitle')),
    recommendedModelsDescription: t(i18n, k('dialogRecommendedModelsDescription')),
    modelNote: (noteKey) => localizedFlowerProviderModelNote(i18n.locale, noteKey),
    enableAll: t(i18n, k('dialogEnableAll')),
    customModelProvider: t(i18n, k('dialogCustomModelProvider')),
    contextSuffix: t(i18n, k('dialogContextSuffix')),
    outputSuffix: t(i18n, k('dialogOutputSuffix')),
    add: t(i18n, k('dialogAdd')),
    remove: t(i18n, k('dialogRemove')),
    text: t(i18n, k('text')),
    imageInput: t(i18n, k('imageInput')),
    enabled: t(i18n, k('dialogEnabled')),
    customModelPlaceholder: t(i18n, k('dialogCustomModelPlaceholder')),
    curatedPresetsOnly: t(i18n, k('dialogCuratedPresetsOnly')),
    addCustomModel: t(i18n, k('dialogAddCustomModel')),
    enabledModelsTitle: t(i18n, k('dialogEnabledModelsTitle')),
    enabledModelsDescription: t(i18n, k('dialogEnabledModelsDescription')),
    noEnabledModels: t(i18n, k('dialogNoEnabledModels')),
    unnamedModel: t(i18n, k('dialogUnnamedModel')),
    textAndImage: t(i18n, k('dialogTextAndImage')),
    textOnly: t(i18n, k('dialogTextOnly')),
    modelIDPending: t(i18n, k('dialogModelIDPending')),
    advancedTitle: t(i18n, k('dialogAdvancedTitle')),
    advancedDescription: t(i18n, k('dialogAdvancedDescription')),
    show: t(i18n, k('dialogShow')),
    hide: t(i18n, k('dialogHide')),
    providerIDPending: t(i18n, k('dialogProviderIDPending')),
    modelName: t(i18n, k('dialogModelName')),
    contextWindow: t(i18n, k('dialogContextWindow')),
    maxOutput: t(i18n, k('dialogMaxOutput')),
    effectiveContextPercent: t(i18n, k('dialogEffectiveContextPercent')),
  };
}
