import type { FlowerSurfaceCopy } from '../../../../internal/flower_ui/src/copy';
import { localizedFlowerProviderModelNote } from '../../../../internal/flower_ui/src/settings/providerModelNotes';
import { localizedFlowerProviderTypeLabels } from '../../../../internal/flower_ui/src/settings/providerTypeLabels';
import type { DesktopI18n } from '../../shared/i18n';

type CopyKey = Parameters<DesktopI18n['t']>[0];

function t(i18n: DesktopI18n, key: CopyKey, params?: Parameters<DesktopI18n['t']>[1]): string {
  return i18n.t(key, params);
}

export function createDesktopFlowerSurfaceCopy(i18n: DesktopI18n): FlowerSurfaceCopy {
  const k = (suffix: string) => `flowerSurface.${suffix}` as CopyKey;
  return {
    chat: {
      loadingSettings: t(i18n, k('chat.loadingSettings')),
      warmupTitle: t(i18n, k('chat.warmupTitle')),
      warmupDetail: t(i18n, k('chat.warmupDetail')),
      warmupComposerPlaceholder: t(i18n, k('chat.warmupComposerPlaceholder')),
      warmupModelLabel: t(i18n, k('chat.warmupModelLabel')),
      configureProviderBeforeChat: t(i18n, k('chat.configureProviderBeforeChat')),
      enterMessageBeforeSending: t(i18n, k('chat.enterMessageBeforeSending')),
      titleFallback: t(i18n, k('chat.titleFallback')),
      ready: t(i18n, k('chat.ready')),
      setupNeeded: t(i18n, k('chat.setupNeeded')),
      settingsLabel: t(i18n, k('chat.settingsLabel')),
      needsProviderNotice: t(i18n, k('chat.needsProviderNotice')),
      openSettings: t(i18n, k('chat.openSettings')),
      placeholder: t(i18n, k('chat.placeholder')),
      fromSource: (source) => t(i18n, k('chat.fromSource'), { source }),
      modelLabel: t(i18n, k('chat.modelLabel')),
      noModelSelected: t(i18n, k('chat.noModelSelected')),
      linkedContextLabel: t(i18n, 'environmentCenter.askFlowerCardContextLabel'),
      handlerBlockedTitle: t(i18n, k('chat.handlerBlockedTitle')),
      handlerStartFailedTitle: t(i18n, k('chat.handlerStartFailedTitle')),
      handlerStillStarting: t(i18n, k('chat.handlerStillStarting')),
      handlerRetry: t(i18n, k('chat.handlerRetry')),
      send: t(i18n, k('chat.send')),
      stop: t(i18n, k('chat.stop')),
      compactContext: t(i18n, k('chat.compactContext')),
      compactChooseThread: t(i18n, k('chat.compactChooseThread')),
      compactFinishInputRequest: t(i18n, k('chat.compactFinishInputRequest')),
      compactNeedsConversation: t(i18n, k('chat.compactNeedsConversation')),
      commandMenuLabel: t(i18n, k('chat.commandMenuLabel')),
      commandCompactContext: t(i18n, k('chat.commandCompactContext')),
      pendingSending: t(i18n, k('chat.pendingSending')),
      pendingQueued: t(i18n, k('chat.pendingQueued')),
      scrollToLatest: t(i18n, k('chat.scrollToLatest')),
      runErrorTitle: t(i18n, k('chat.runErrorTitle')),
      runErrorActions: {
        updateAPIKey: t(i18n, k('chat.runErrorActionUpdateAPIKey')),
        addAPIKey: t(i18n, k('chat.runErrorActionAddAPIKey')),
        switchModel: t(i18n, k('chat.runErrorActionSwitchModel')),
        openSettings: t(i18n, k('chat.runErrorActionOpenSettings')),
      },
      runErrors: {
        providerAuthFailed: t(i18n, k('chat.runErrorProviderAuthFailed')),
        providerMissingKey: t(i18n, k('chat.runErrorProviderMissingKey')),
        providerRateLimited: t(i18n, k('chat.runErrorProviderRateLimited')),
        providerUnreachable: t(i18n, k('chat.runErrorProviderUnreachable')),
        providerModelUnavailable: t(i18n, k('chat.runErrorProviderModelUnavailable')),
        floretEngineFailed: t(i18n, k('chat.runErrorFloretEngineFailed')),
        runtimeRestarted: t(i18n, k('chat.runErrorRuntimeRestarted')),
      },
      messageErrorTitle: t(i18n, k('chat.messageErrorTitle')),
      messageErrorFallback: t(i18n, k('chat.messageErrorFallback')),
      copyCode: t(i18n, k('chat.copyCode')),
      codeCopied: t(i18n, k('chat.codeCopied')),
      copyMessage: t(i18n, k('chat.copyMessage')),
      messageCopied: t(i18n, k('chat.messageCopied')),
      loadErrorTitle: t(i18n, k('chat.loadErrorTitle')),
      threadLoadErrorTitle: t(i18n, k('chat.threadLoadErrorTitle')),
      threadLoading: t(i18n, k('chat.threadLoading')),
      composerErrorTitle: t(i18n, k('chat.composerErrorTitle')),
      toolStatuses: {
        pending: t(i18n, k('chat.toolStatusPending')),
        running: t(i18n, k('chat.toolStatusRunning')),
        waiting: t(i18n, k('chat.toolStatusWaiting')),
        success: t(i18n, k('chat.toolStatusSuccess')),
        error: t(i18n, k('chat.toolStatusError')),
        canceled: t(i18n, k('chat.toolStatusCanceled')),
      },
      toolApprovalRequired: t(i18n, k('chat.toolApprovalRequired')),
      toolApprovalStates: {
        requested: t(i18n, k('chat.toolApprovalStateRequested')),
        approved: t(i18n, k('chat.toolApprovalStateApproved')),
        rejected: t(i18n, k('chat.toolApprovalStateRejected')),
        timed_out: t(i18n, k('chat.toolApprovalStateTimedOut')),
        canceled: t(i18n, k('chat.toolApprovalStateCanceled')),
      },
      toolApprovalState: (state) => t(i18n, k('chat.toolApprovalState'), { state }),
      toolApprovalApprove: t(i18n, k('chat.toolApprovalApprove')),
      toolApprovalReject: t(i18n, k('chat.toolApprovalReject')),
      toolApprovalSubmitting: t(i18n, k('chat.toolApprovalSubmitting')),
      toolApprovalUnavailable: t(i18n, k('chat.toolApprovalUnavailable')),
      toolApprovalCommand: t(i18n, k('chat.toolApprovalCommand')),
      toolApprovalCommandText: t(i18n, k('chat.toolApprovalCommandText')),
      toolApprovalShowCommand: t(i18n, k('chat.toolApprovalShowCommand')),
      toolApprovalCopy: t(i18n, k('chat.toolApprovalCopy')),
      toolApprovalCopyCommand: t(i18n, k('chat.toolApprovalCopyCommand')),
      toolApprovalCopyCwd: t(i18n, k('chat.toolApprovalCopyCwd')),
      toolApprovalCopied: t(i18n, k('chat.toolApprovalCopied')),
      toolApprovalSubtaskSuffix: (subagentID) => t(i18n, k('chat.toolApprovalSubtaskSuffix'), { subagent: subagentID }),
      toolApprovalApproveAction: (label, subtask) => t(i18n, k('chat.toolApprovalApproveAction'), { label, subtask }),
      toolApprovalRejectAction: (label, subtask) => t(i18n, k('chat.toolApprovalRejectAction'), { label, subtask }),
      threadApprovalPanelLabel: t(i18n, k('chat.threadApprovalPanelLabel')),
      threadApprovalPanelTitle: (count) => t(i18n, k('chat.threadApprovalPanelTitle'), { count }),
      delegatedApprovalStatus: {
        unavailable: t(i18n, k('chat.delegatedApprovalStatusUnavailable')),
        pending: t(i18n, k('chat.delegatedApprovalStatusPending')),
        delivered: t(i18n, k('chat.delegatedApprovalStatusDelivered')),
        failed: t(i18n, k('chat.delegatedApprovalStatusFailed')),
        handledInCurrentThread: t(i18n, k('chat.delegatedApprovalStatusHandledInCurrentThread')),
        deliveryInProgress: t(i18n, k('chat.delegatedApprovalStatusDeliveryInProgress')),
        deliveryDelivered: t(i18n, k('chat.delegatedApprovalStatusDeliveryDelivered')),
        deliveryNeedsReview: t(i18n, k('chat.delegatedApprovalStatusDeliveryNeedsReview')),
      },
      readOnlyComposerLabel: t(i18n, k('chat.readOnlyComposerLabel')),
      inputRequestTitle: t(i18n, k('chat.inputRequestTitle')),
      inputRequestDescription: t(i18n, k('chat.inputRequestDescription')),
      inputRequestSubmit: t(i18n, k('chat.inputRequestSubmit')),
      inputRequestRetry: t(i18n, k('chat.inputRequestRetry')),
      inputRequestAnswerRequired: t(i18n, k('chat.inputRequestAnswerRequired')),
      inputRequestSubmitting: t(i18n, k('chat.inputRequestSubmitting')),
      inputRequestComposerPlaceholder: t(i18n, k('chat.inputRequestComposerPlaceholder')),
      inputRequestChoicePlaceholder: t(i18n, k('chat.inputRequestChoicePlaceholder')),
      modelStatus: {
        preparing: t(i18n, k('chat.modelStatusPreparing')),
        waitingResponse: t(i18n, k('chat.modelStatusWaitingResponse')),
        streaming: t(i18n, k('chat.modelStatusStreaming')),
        retrying: t(i18n, k('chat.modelStatusRetrying')),
        finalizing: t(i18n, k('chat.modelStatusFinalizing')),
      },
      contextIndicator: {
        label: t(i18n, k('chat.contextIndicatorLabel')),
        stable: t(i18n, k('chat.contextIndicatorStable')),
        nearThreshold: t(i18n, k('chat.contextIndicatorNearThreshold')),
        willCompact: t(i18n, k('chat.contextIndicatorWillCompact')),
        hardLimit: t(i18n, k('chat.contextIndicatorHardLimit')),
        estimated: t(i18n, k('chat.contextIndicatorEstimated')),
        unknown: t(i18n, k('chat.contextIndicatorUnknown')),
        unknownPercent: t(i18n, k('chat.contextIndicatorUnknownPercent')),
        unavailable: t(i18n, k('chat.contextIndicatorUnavailable')),
        usedLabel: t(i18n, k('chat.contextIndicatorUsedLabel')),
        ratioLabel: t(i18n, k('chat.contextIndicatorRatioLabel')),
        thresholdLabel: t(i18n, k('chat.contextIndicatorThresholdLabel')),
        safeLimitLabel: t(i18n, k('chat.contextIndicatorSafeLimitLabel')),
        statusLabel: t(i18n, k('chat.contextIndicatorStatusLabel')),
        usage: (used, total) => t(i18n, k('chat.contextIndicatorUsage'), { used, total }),
        percent: (percent) => t(i18n, k('chat.contextIndicatorPercent'), { percent }),
      },
      compactionDivider: {
        compacting: t(i18n, k('chat.compactionDividerCompacting')),
        compacted: t(i18n, k('chat.compactionDividerCompacted')),
        failed: t(i18n, k('chat.compactionDividerFailed')),
        cancelled: t(i18n, k('chat.compactionDividerCancelled')),
        fallback: t(i18n, k('chat.compactionDividerFallback')),
        tokenChange: (before, after) => t(i18n, k('chat.compactionDividerTokenChange'), { before, after }),
      },
      conversationsAria: t(i18n, k('chat.conversationsAria')),
      resizeConversationsLabel: t(i18n, k('chat.resizeConversationsLabel')),
      entryLabel: t(i18n, k('chat.entryLabel')),
      newChat: t(i18n, k('chat.newChat')),
    },
    threadList: {
      title: t(i18n, k('threadList.title')),
      description: t(i18n, k('threadList.description')),
      warmupDescription: t(i18n, k('threadList.warmupDescription')),
      refreshLabel: t(i18n, k('threadList.refreshLabel')),
      searchPlaceholder: t(i18n, k('threadList.searchPlaceholder')),
      empty: t(i18n, k('threadList.empty')),
      untitled: t(i18n, k('threadList.untitled')),
      working: t(i18n, k('threadList.working')),
      unread: t(i18n, k('threadList.unread')),
      deleteLabel: (title) => t(i18n, k('threadList.deleteLabel'), { title }),
      contextMenuLabel: (title) => t(i18n, k('threadList.contextMenuLabel'), { title }),
      copyThreadID: t(i18n, k('threadList.copyThreadID')),
      copyWorkingDirectory: t(i18n, k('threadList.copyWorkingDirectory')),
      threadIDLabel: t(i18n, k('threadList.threadIDLabel')),
      workingDirectoryLabel: t(i18n, k('threadList.workingDirectoryLabel')),
      copied: (label) => t(i18n, k('threadList.copied'), { label }),
      fork: t(i18n, k('threadList.fork')),
      pin: t(i18n, k('threadList.pin')),
      unpin: t(i18n, k('threadList.unpin')),
      pinnedGroup: t(i18n, k('threadList.pinnedGroup')),
      pinnedBadge: t(i18n, k('threadList.pinnedBadge')),
      rename: t(i18n, k('threadList.rename')),
      renameTitle: t(i18n, k('threadList.renameTitle')),
      renameNameLabel: t(i18n, k('threadList.renameNameLabel')),
      cancel: t(i18n, k('threadList.cancel')),
      save: t(i18n, k('threadList.save')),
      saving: t(i18n, k('threadList.saving')),
      now: t(i18n, k('threadList.now')),
      minutes: (count) => t(i18n, k('threadList.minutes'), { count }),
      hours: (count) => t(i18n, k('threadList.hours'), { count }),
      days: (count) => t(i18n, k('threadList.days'), { count }),
      statuses: {
        idle: t(i18n, k('threadList.statusIdle')),
        running: t(i18n, k('threadList.statusRunning')),
        waiting_user: t(i18n, k('threadList.statusWaitingUser')),
        waiting_approval: t(i18n, k('threadList.statusWaitingApproval')),
        failed: t(i18n, k('threadList.statusFailed')),
        success: t(i18n, k('threadList.statusSuccess')),
        canceled: t(i18n, k('threadList.statusCanceled')),
        read_only: t(i18n, k('threadList.statusReadOnly')),
      },
      groups: {
        today: t(i18n, k('threadList.groupToday')),
        yesterday: t(i18n, k('threadList.groupYesterday')),
        this_week: t(i18n, k('threadList.groupThisWeek')),
        older: t(i18n, k('threadList.groupOlder')),
      },
    },
    emptyState: {
      title: t(i18n, k('emptyState.title')),
      description: t(i18n, k('emptyState.description')),
      suggestions: [
        {
          title: t(i18n, k('emptyState.reviewTitle')),
          description: t(i18n, k('emptyState.reviewDescription')),
          prompt: t(i18n, k('emptyState.reviewPrompt')),
        },
        {
          title: t(i18n, k('emptyState.transferTitle')),
          description: t(i18n, k('emptyState.transferDescription')),
          prompt: t(i18n, k('emptyState.transferPrompt')),
        },
        {
          title: t(i18n, k('emptyState.explainTitle')),
          description: t(i18n, k('emptyState.explainDescription')),
          prompt: t(i18n, k('emptyState.explainPrompt')),
        },
        {
          title: t(i18n, k('emptyState.workflowTitle')),
          description: t(i18n, k('emptyState.workflowDescription')),
          prompt: t(i18n, k('emptyState.workflowPrompt')),
        },
      ],
      sendKeyLabel: t(i18n, k('emptyState.sendKeyLabel')),
      newLineKeyLabel: t(i18n, k('emptyState.newLineKeyLabel')),
    },
    subagents: createDesktopFlowerSubagentsCopy(i18n),
    settings: createDesktopFlowerSettingsCopy(i18n),
  };
}

function createDesktopFlowerSubagentsCopy(i18n: DesktopI18n): FlowerSurfaceCopy['subagents'] {
  const k = (suffix: string) => `flowerSurface.subagents.${suffix}` as CopyKey;
  return {
    title: t(i18n, k('title')),
    description: t(i18n, k('description')),
    openLabel: t(i18n, k('openLabel')),
    openThread: t(i18n, k('openThread')),
    backToChat: t(i18n, k('backToChat')),
    emptyTitle: t(i18n, k('emptyTitle')),
    emptyDescription: t(i18n, k('emptyDescription')),
    activeLabel: t(i18n, k('activeLabel')),
    completedLabel: t(i18n, k('completedLabel')),
    threadIDLabel: t(i18n, k('threadIDLabel')),
    lastMessageLabel: t(i18n, k('lastMessageLabel')),
    unavailableThread: t(i18n, k('unavailableThread')),
    readOnlyComposerLabel: t(i18n, k('readOnlyComposerLabel')),
    statusLabels: {
      queued: t(i18n, k('status.queued')),
      running: t(i18n, k('status.running')),
      waiting_input: t(i18n, k('status.waitingInput')),
      completed: t(i18n, k('status.completed')),
      failed: t(i18n, k('status.failed')),
      canceled: t(i18n, k('status.canceled')),
      timed_out: t(i18n, k('status.timedOut')),
      unknown: t(i18n, k('status.unknown')),
    },
    typeLabels: {
      explore: t(i18n, k('types.explore')),
      worker: t(i18n, k('types.worker')),
      reviewer: t(i18n, k('types.reviewer')),
      unknown: t(i18n, k('types.unknown')),
    },
    activity: {
      actions: {
        spawn: t(i18n, k('activity.actions.spawn')),
        send_input: t(i18n, k('activity.actions.sendInput')),
        wait: t(i18n, k('activity.actions.wait')),
        list: t(i18n, k('activity.actions.list')),
        inspect: t(i18n, k('activity.actions.inspect')),
        close: t(i18n, k('activity.actions.close')),
        close_all: t(i18n, k('activity.actions.closeAll')),
        unknown: t(i18n, k('activity.actions.unknown')),
      },
      titleVerbs: {
        spawn: t(i18n, k('activity.titleVerbs.spawn')),
        send_input: t(i18n, k('activity.titleVerbs.sendInput')),
        wait: t(i18n, k('activity.titleVerbs.wait')),
        list: t(i18n, k('activity.titleVerbs.list')),
        inspect: t(i18n, k('activity.titleVerbs.inspect')),
        close: t(i18n, k('activity.titleVerbs.close')),
        close_all: t(i18n, k('activity.titleVerbs.closeAll')),
      },
      labels: {
        approval: t(i18n, k('activity.labels.approval')),
        action: t(i18n, k('activity.labels.action')),
        status: t(i18n, k('activity.labels.status')),
        thread: t(i18n, k('activity.labels.thread')),
        subagent: t(i18n, k('activity.labels.subagent')),
        task: t(i18n, k('activity.labels.task')),
        title: t(i18n, k('activity.labels.title')),
        profile: t(i18n, k('activity.labels.profile')),
        target: t(i18n, k('activity.labels.target')),
        targets: t(i18n, k('activity.labels.targets')),
        ids: t(i18n, k('activity.labels.ids')),
        accepted: t(i18n, k('activity.labels.accepted')),
        closed: t(i18n, k('activity.labels.closed')),
        affected: t(i18n, k('activity.labels.affected')),
        agents: t(i18n, k('activity.labels.agents')),
        total: t(i18n, k('activity.labels.total')),
        runningOnly: t(i18n, k('activity.labels.runningOnly')),
        queued: t(i18n, k('activity.labels.queued')),
        running: t(i18n, k('activity.labels.running')),
        waiting: t(i18n, k('activity.labels.waiting')),
        completed: t(i18n, k('activity.labels.completed')),
        failed: t(i18n, k('activity.labels.failed')),
        canceled: t(i18n, k('activity.labels.canceled')),
        timedOut: t(i18n, k('activity.labels.timedOut')),
        requested: t(i18n, k('activity.labels.requested')),
        found: t(i18n, k('activity.labels.found')),
        missing: t(i18n, k('activity.labels.missing')),
        missingIds: t(i18n, k('activity.labels.missingIds')),
        lastMessage: t(i18n, k('activity.labels.lastMessage')),
        waitingPrompt: t(i18n, k('activity.labels.waitingPrompt')),
        canSendInput: t(i18n, k('activity.labels.canSendInput')),
        canInterrupt: t(i18n, k('activity.labels.canInterrupt')),
        canClose: t(i18n, k('activity.labels.canClose')),
        runtime: t(i18n, k('activity.labels.runtime')),
        summary: t(i18n, k('activity.labels.summary')),
        details: t(i18n, k('activity.labels.details')),
        errorCode: t(i18n, k('activity.labels.errorCode')),
        errorMessage: t(i18n, k('activity.labels.errorMessage')),
        retryable: t(i18n, k('activity.labels.retryable')),
      },
      values: {
        yes: t(i18n, k('activity.values.yes')),
        no: t(i18n, k('activity.values.no')),
      },
      agentsCount: (count) => t(i18n, k('activity.agentsCount'), { count }),
    },
  };
}

function createDesktopFlowerSettingsCopy(i18n: DesktopI18n): FlowerSurfaceCopy['settings'] {
  const k = (suffix: string) => `flowerSurface.settings.${suffix}` as CopyKey;
  return {
    title: t(i18n, k('title')),
    backToChat: t(i18n, k('backToChat')),
    description: t(i18n, k('description')),
    currentModel: t(i18n, k('currentModel')),
    noModelSelected: t(i18n, k('noModelSelected')),
    text: t(i18n, k('text')),
    imageInput: t(i18n, k('imageInput')),
    selectModelPlaceholder: t(i18n, k('selectModelPlaceholder')),
    defaultPermissionTitle: t(i18n, k('defaultPermissionTitle')),
    defaultPermissionDescription: t(i18n, k('defaultPermissionDescription')),
    defaultPermissionBadge: t(i18n, k('defaultPermissionBadge')),
    permissionTypes: {
      readonly: {
        label: t(i18n, k('permissionReadonlyLabel')),
        description: t(i18n, k('permissionReadonlyDescription')),
      },
      approval_required: {
        label: t(i18n, k('permissionApprovalRequiredLabel')),
        description: t(i18n, k('permissionApprovalRequiredDescription')),
      },
      full_access: {
        label: t(i18n, k('permissionFullAccessLabel')),
        description: t(i18n, k('permissionFullAccessDescription')),
      },
    },
    providersTitle: t(i18n, k('providersTitle')),
    providersDescription: t(i18n, k('providersDescription')),
    managedByLocalAIProfileTitle: t(i18n, k('managedByLocalAIProfileTitle')),
    managedByLocalAIProfileDescription: t(i18n, k('managedByLocalAIProfileDescription')),
    managedByLocalAIProfileReady: t(i18n, k('managedByLocalAIProfileReady')),
    managedByLocalAIProfileNeedsKey: t(i18n, k('managedByLocalAIProfileNeedsKey')),
    managedByLocalAIProfileModelCount: (count) => t(i18n, k('managedByLocalAIProfileModelCount'), { count }),
    managedByLocalAIProfileMissingKeys: (providers) => t(i18n, k('managedByLocalAIProfileMissingKeys'), { providers }),
    managedByLocalAIProfileOpenLocal: t(i18n, k('managedByLocalAIProfileOpenLocal')),
    addProvider: t(i18n, k('addProvider')),
    noProviders: t(i18n, k('noProviders')),
    defaultProvider: t(i18n, k('defaultProvider')),
    editProvider: t(i18n, k('editProvider')),
    removeProvider: t(i18n, k('removeProvider')),
    apiKey: t(i18n, k('apiKey')),
    ready: t(i18n, k('ready')),
    needsKey: t(i18n, k('needsKey')),
    models: t(i18n, k('models')),
    web: t(i18n, k('web')),
    vision: t(i18n, k('vision')),
    terminalLimitsTitle: t(i18n, k('terminalLimitsTitle')),
    terminalLimitsDescription: t(i18n, k('terminalLimitsDescription')),
    defaultTimeout: t(i18n, k('defaultTimeout')),
    maximumTimeout: t(i18n, k('maximumTimeout')),
    webSearchNotSupported: t(i18n, k('webSearchNotSupported')),
    webSearchDisabled: t(i18n, k('webSearchDisabled')),
    openAIBuiltIn: t(i18n, k('openAIBuiltIn')),
    braveSearch: t(i18n, k('braveSearch')),
    needsBraveKey: t(i18n, k('needsBraveKey')),
    providerTypeLabels: localizedFlowerProviderTypeLabels(i18n.locale),
    builtInWebSearch: {
      openai: t(i18n, k('openAIBuiltInWebSearch')),
      moonshot: t(i18n, k('kimiBuiltInWebSearch')),
      chatglm: t(i18n, k('glmBuiltInWebSearch')),
      deepseek: t(i18n, k('deepSeekBuiltInWebSearch')),
      qwen: t(i18n, k('qwenBuiltInWebSearch')),
    },
    autoSave: {
      saving: t(i18n, k('autoSaveSaving')),
      saveFailed: t(i18n, k('autoSaveFailed')),
      unsaved: t(i18n, k('autoSaveUnsaved')),
      saved: t(i18n, k('autoSaveSaved')),
      ready: t(i18n, k('autoSaveReady')),
    },
    validation: {
      providerIDRequired: t(i18n, k('providerIDRequired')),
      providerIDNoSlash: t(i18n, k('providerIDNoSlash')),
      duplicateProviderID: (providerID) => t(i18n, k('duplicateProviderID'), { providerID }),
      providerRequiresBaseURL: (providerName) => t(i18n, k('providerRequiresBaseURL'), { providerName }),
      providerInvalidBaseURL: (providerName) => t(i18n, k('providerInvalidBaseURL'), { providerName }),
      providerBaseURLProtocol: (providerName) => t(i18n, k('providerBaseURLProtocol'), { providerName }),
      providerNeedsModel: (providerName) => t(i18n, k('providerNeedsModel'), { providerName }),
      providerUnnamedModel: (providerName) => t(i18n, k('providerUnnamedModel'), { providerName }),
      modelNameNoSlash: t(i18n, k('modelNameNoSlash')),
      duplicateModel: (providerName, modelName) => t(i18n, k('duplicateModel'), { providerName, modelName }),
      modelNeedsContextWindow: (modelName) => t(i18n, k('modelNeedsContextWindow'), { modelName }),
      selectCurrentModel: t(i18n, k('selectCurrentModel')),
      currentModelUnavailable: (modelID) => t(i18n, k('currentModelUnavailable'), { modelID }),
      terminalTimeoutPositive: t(i18n, k('terminalTimeoutPositive')),
      terminalTimeoutOrder: t(i18n, k('terminalTimeoutOrder')),
    },
    dialog: createDesktopFlowerProviderDialogCopy(i18n),
  };
}

function createDesktopFlowerProviderDialogCopy(i18n: DesktopI18n): FlowerSurfaceCopy['settings']['dialog'] {
  const k = (suffix: string) => `flowerSurface.settings.${suffix}` as CopyKey;
  return {
    addTitle: t(i18n, k('dialogAddTitle')),
    editTitle: t(i18n, k('dialogEditTitle')),
    discard: t(i18n, k('dialogDiscard')),
    saveProvider: t(i18n, k('dialogSaveProvider')),
    providerRemoved: t(i18n, k('dialogProviderRemoved')),
    providerTypeTitle: t(i18n, k('dialogProviderTypeTitle')),
    providerTypeDescription: t(i18n, k('dialogProviderTypeDescription')),
    current: t(i18n, k('dialogCurrent')),
    collapse: t(i18n, k('dialogCollapse')),
    configure: t(i18n, k('dialogConfigure')),
    providerTypeLabels: localizedFlowerProviderTypeLabels(i18n.locale),
    providerTypeHints: {
      openai: t(i18n, k('dialogNativeConnection')),
      anthropic: t(i18n, k('dialogNativeConnection')),
      moonshot: t(i18n, k('dialogNativeConnection')),
      chatglm: t(i18n, k('dialogNativeConnection')),
      deepseek: t(i18n, k('dialogNativeConnection')),
      qwen: t(i18n, k('dialogNativeConnection')),
      openrouter: 'Dynamic model metadata',
      xai: 'OpenAI-compatible native endpoint',
      groq: 'OpenAI-compatible native endpoint',
      ollama: 'Local OpenAI-compatible endpoint',
      openai_compatible: t(i18n, k('dialogCustomEndpoint')),
    },
    connectionTitle: t(i18n, k('dialogConnectionTitle')),
    connectionDescription: t(i18n, k('dialogConnectionDescription')),
    connectionName: t(i18n, k('dialogConnectionName')),
    apiKey: t(i18n, k('dialogAPIKey')),
    storedKeyKept: t(i18n, k('dialogStoredKeyKept')),
    requiredBeforeUse: t(i18n, k('dialogRequiredBeforeUse')),
    pasteAPIKey: t(i18n, k('dialogPasteAPIKey')),
    required: t(i18n, k('dialogRequired')),
    baseURL: t(i18n, k('dialogBaseURL')),
    webSearch: t(i18n, k('dialogWebSearch')),
    disabled: t(i18n, k('dialogDisabled')),
    openAIBuiltIn: t(i18n, k('dialogOpenAIBuiltIn')),
    braveSearch: t(i18n, k('dialogBraveSearch')),
    requiredForBraveSearch: t(i18n, k('dialogRequiredForBraveSearch')),
    braveAPIKey: t(i18n, k('dialogBraveAPIKey')),
    storedBraveKeyKept: t(i18n, k('dialogStoredBraveKeyKept')),
    pasteBraveAPIKey: t(i18n, k('dialogPasteBraveAPIKey')),
    keyReady: t(i18n, k('dialogKeyReady')),
    needsKey: t(i18n, k('dialogNeedsKey')),
    braveKeyReady: t(i18n, k('dialogBraveKeyReady')),
    needsBraveKey: t(i18n, k('dialogNeedsBraveKey')),
    builtInWebSearch: {
      openai: t(i18n, k('openAIBuiltInWebSearch')),
      moonshot: t(i18n, k('kimiBuiltInWebSearch')),
      chatglm: t(i18n, k('glmBuiltInWebSearch')),
      deepseek: t(i18n, k('deepSeekBuiltInWebSearch')),
      qwen: t(i18n, k('qwenBuiltInWebSearch')),
    },
    recommendedModelsTitle: t(i18n, k('dialogRecommendedModelsTitle')),
    recommendedModelsDescription: t(i18n, k('dialogRecommendedModelsDescription')),
    modelNote: (noteKey) => localizedFlowerProviderModelNote(i18n.locale, noteKey),
    addAllPresets: t(i18n, k('dialogAddAllPresets')),
    customModelProvider: t(i18n, k('dialogCustomModelProvider')),
    contextSuffix: t(i18n, k('dialogContextSuffix')),
    outputSuffix: t(i18n, k('dialogOutputSuffix')),
    add: t(i18n, k('dialogAdd')),
    remove: t(i18n, k('dialogRemove')),
    text: t(i18n, k('text')),
    imageInput: t(i18n, k('imageInput')),
    selected: t(i18n, k('dialogSelected')),
    customModelPlaceholder: t(i18n, k('dialogCustomModelPlaceholder')),
    curatedPresetsOnly: t(i18n, k('dialogCuratedPresetsOnly')),
    addCustomModel: t(i18n, k('dialogAddCustomModel')),
    selectedModelsTitle: t(i18n, k('dialogSelectedModelsTitle')),
    selectedModelsDescription: t(i18n, k('dialogSelectedModelsDescription')),
    noSelectedModels: t(i18n, k('dialogNoSelectedModels')),
    unnamedModel: t(i18n, k('dialogUnnamedModel')),
    textAndImage: t(i18n, k('dialogTextAndImage')),
    textOnly: t(i18n, k('dialogTextOnly')),
    modelIDPending: t(i18n, k('dialogModelIDPending')),
    advancedTitle: t(i18n, k('dialogAdvancedTitle')),
    advancedDescription: t(i18n, k('dialogAdvancedDescription')),
    show: t(i18n, k('dialogShow')),
    hide: t(i18n, k('dialogHide')),
    providerIDPending: t(i18n, k('dialogProviderIDPending')),
    modelName: t(i18n, k('dialogModelName')),
    providerModelID: t(i18n, k('dialogProviderModelID')),
    contextWindow: t(i18n, k('dialogContextWindow')),
    maxOutput: t(i18n, k('dialogMaxOutput')),
    effectiveContextPercent: t(i18n, k('dialogEffectiveContextPercent')),
  };
}
