export const REDEVEN_WORKBENCH_WHEEL_INTERACTIVE_ATTR = 'data-floe-canvas-wheel-interactive';
export const REDEVEN_WORKBENCH_WHEEL_INTERACTIVE_SELECTOR =
  `[${REDEVEN_WORKBENCH_WHEEL_INTERACTIVE_ATTR}="true"]`;
export const REDEVEN_WORKBENCH_WHEEL_INTERACTIVE_PROPS = {
  [REDEVEN_WORKBENCH_WHEEL_INTERACTIVE_ATTR]: 'true',
} as const;
