export const REDEVEN_WORKBENCH_WHEEL_INTERACTIVE_ATTR = 'data-floe-canvas-wheel-interactive';
export const REDEVEN_WORKBENCH_WHEEL_INTERACTIVE_SELECTOR =
  `[${REDEVEN_WORKBENCH_WHEEL_INTERACTIVE_ATTR}="true"]`;
export const REDEVEN_WORKBENCH_WHEEL_ROLE_ATTR = 'data-redeven-workbench-wheel-role';
export const REDEVEN_WORKBENCH_WHEEL_ROLE_LOCAL_SCROLL_VIEWPORT = 'local-scroll-viewport';
export const REDEVEN_WORKBENCH_WHEEL_ROLE_LAYOUT_ONLY = 'layout-only';

export const REDEVEN_WORKBENCH_LOCAL_SCROLL_VIEWPORT_PROPS = {
  [REDEVEN_WORKBENCH_WHEEL_INTERACTIVE_ATTR]: 'true',
  [REDEVEN_WORKBENCH_WHEEL_ROLE_ATTR]: REDEVEN_WORKBENCH_WHEEL_ROLE_LOCAL_SCROLL_VIEWPORT,
} as const;

export const REDEVEN_WORKBENCH_WHEEL_LAYOUT_ONLY_PROPS = {
  [REDEVEN_WORKBENCH_WHEEL_ROLE_ATTR]: REDEVEN_WORKBENCH_WHEEL_ROLE_LAYOUT_ONLY,
} as const;

export const REDEVEN_WORKBENCH_WHEEL_INTERACTIVE_PROPS =
  REDEVEN_WORKBENCH_LOCAL_SCROLL_VIEWPORT_PROPS;
