export const computerUseEnUS = {
  managed: "Flower managed browser",
  system: "Connected system browser",
  connectionTitle: "Connect Chrome",
  connectionHint: "Connect Chrome to continue this task automatically.",
  noFrame: "No screenshot available",
  frameConnecting: "Connecting to the view…",
  frameDisconnected: "View connection interrupted",
  frameStale: "Last captured view · not live",
  reveal: "View in browser",
  revealFailed: "Unable to show the browser tab. Check that the browser is connected.",
  profileName: 'Profile name',
  createProfile: 'Create profile',
  disconnect: 'Disconnect',
  extension: 'Chrome extension',
  extensionHint: "Install the Flower Browser extension once to let Flower use Chrome.",
  setupAlreadyInstalled: "Already installed",
  setupInstalled: "Installed, continue",
  setupBack: "Back",
  setupHelp: "Need help?",
  setupHostHint: "Use Google Chrome on the computer running this environment. Safari and other browsers are not supported yet.",
  setupDeveloperMode: "Turn on Developer mode in the top right.",
  setupLoadUnpacked: "Click Load unpacked in the top left.",
  setupChooseFolder: "In the folder picker, start from your home folder:",
  setupHome: "Home",
  setupFolderHint: "Select the last folder and confirm. Keep it here after installation.",
  setupLabelsHint: "Button names may differ with Chrome’s language or version. In English, look for Developer mode and Load unpacked.",
  setupPreparing: 'Preparing the connection…',
  setupConfirming: 'Waiting for your confirmation in Chrome…',
  setupConnected: 'Chrome connected · continuing…',
  setupFailed: 'Unable to check the connection. Keep this environment running, then try again.',
  setupTimeout: 'No connection detected yet. Finish the steps in Chrome, then check again.',
  setupInstallTitle: "Install extension",
  setupConfirmTitle: "Connect Chrome",
  setupConfirmHint: "On the page that opens in Chrome, click Connect. Your task will continue automatically.",
  openExtensions: "Open Chrome extensions",
  openExtensionFolder: 'Show folder',
  copyExtensionPath: 'Copy folder path',
  pathCopied: 'Path copied',
  openConnection: "Connect in Chrome",
  setupOpenFailed: 'Unable to open Chrome or the folder. Make sure Google Chrome is installed on the computer running this environment and try again. Remote environments open it on that computer.',
  retryConnection: 'Check connection again',
  extensionPath: 'Extension folder',
  newTab: 'New background tab',
  title: 'Browser and desktop',
  description: 'Flower chooses the page or application for your task. View its current connection, switch when needed, or manage access.',
  target: 'Currently using',
  automatic: 'Chosen automatically',
  automaticHint: 'Flower prefers your connected browser and creates a separate task tab. No selection is needed.',
  switchTarget: 'Switch page or application',
  manageConnections: 'Manage connections',
  searchTargets: 'Search pages and applications',
  browserPages: 'Browser pages',
  applicationWindows: 'Application windows',
  inUse: 'Used by another task',
  disconnected: 'Not connected',
  selectionStale: 'This page or window changed. Refresh the list and choose it again.',
  refresh: 'Refresh',
  noTargets: 'No computer targets are available.',
  setupRequired: 'Setup required',
  permissionRequired: 'System permission required',
  sites: 'Allowed sites',
  sitePlaceholder: 'https://example.com',
  add: 'Add',
  remove: 'Remove access',
  apps: 'Allowed applications',
  foreground: 'Allow temporary desktop use',
  foregroundHint: 'Flower may bring an application forward to complete your task. Use Stop in Flower when you want to take control.',
  save: 'Save access',
  saving: 'Saving…',
  saved: 'Access saved',
  failed: 'Unable to update the connection. Refresh and try again.',
  close: 'Close',
  profile: 'Browser profile',
  tab: 'Browser tab',
  chooseProfile: 'Select a profile',
  chooseTab: 'Select a tab',
  listTabs: 'Find tabs',
  noTabs: 'No available tabs were found.',
  connect: 'Connect tab',
  connecting: 'Connecting…',
  connected: 'Connected',
  advanced: 'Connect a self-managed Chromium browser',
  endpoint: 'Browser debugging endpoint',
  background: 'Running in background',
  usingDesktop: 'Using the desktop',
  waitingControl: 'Waiting for you',
  requestedAccess: 'Access needed to continue',
  grantRequested: 'Add requested access',
  revokeAll: 'Revoke all access',
  allowContinue: 'Allow and continue',
  fullAccessTitle: 'Full access is enabled',
  fullAccessHint: 'Websites, applications, and temporary desktop use are already allowed for this conversation. Choose Approval required in conversation settings to request confirmation.',
  authorizedHint: 'This paused step is already authorized by full access. Continue the task; Flower will check the page before resuming.',
  continueTask: 'Continue task',
  accessFailed: 'Access could not be saved. Try again; Flower has not continued.',
  accessTitle: 'Allow task access',
  siteTitle: 'Allow website access',
  accessHint: 'Flower needs the access listed below for this conversation. Allow it to continue automatically; no manual browser operation is needed.',
  targetTitle: 'Continue the browser task',
  targetHint: 'Continue the task. Flower will discover the available pages and choose the next page for you.',
  loginTitle: 'Sign in on the page',
  loginHint: 'Open the page and finish signing in. Enter passwords there, not in this conversation. Then choose Done, continue.',
  verificationTitle: 'Enter the verification code',
  verificationHint: 'Open the page and enter the one-time code there. Do not send the code in this conversation. Then choose Done, continue.',
  captchaTitle: 'Complete the CAPTCHA',
  captchaHint: 'Open the page and complete its human verification challenge. Then choose Done, continue; Flower will check the page before resuming.',
  privateTitle: 'Complete the private input',
  privateHint: 'Open the page and finish the password or verification field there. Private input stays out of the conversation. Then choose Done, continue.',
  inspectionTitle: 'Check the current page',
  inspectionHint: 'Flower could not safely inspect the page. Open it to check its state; a sign-in requirement has not been confirmed. Then choose Done, continue to check again.',
  untrustedTitle: 'Review unexpected page instructions',
  untrustedHint: 'The page contains instructions aimed at the agent. Open the page and leave or dismiss that content before continuing.',
  pausedTitle: 'Actions are paused',
  pausedHint: 'Finish your changes on the page or application, then choose Done, continue when Flower may resume.',
};
export type FlowerComputerCopy = { readonly [Key in keyof typeof computerUseEnUS]: string };
export function localizedComputerCopy(t: (key: string) => string): FlowerComputerCopy {
  return Object.fromEntries(Object.keys(computerUseEnUS).map(key => [key, t(`flowerSurface.computer.${key}`)])) as FlowerComputerCopy;
}
