export const computerUseEnUS = {
  browserInstallHint: "Choose how to install it, or turn it off to stop installation prompts.",
  browserInstallTitle: "Set up the built-in browser",
  browserSettings: "Browser settings",
  browserDisabled: "Disabled",
  browserWrongPackage: "This package does not match the required version or platform. Choose the matching ZIP.",
  browserInstallLocation: "Installation location",
  browserContinueWithout: "Continue without this browser",
  browserContinue: "Continue task",
  browserReadyHint: "Ready for web tasks. Website sign-ins are saved separately.",
  browserConfirmDownload: "Download and install",
  browserConfirmUpload: "Upload and install",
  browserConsentHint: "Nothing downloads until you confirm.",
  browserGetPackage: "Download the matching package",
  browserFileHint: "Package for the environment shown above",
  browserChooseFile: "Choose ZIP file",
  browserDesktopRequired: "Open in Desktop to upload a local package.",
  browserUploadHint: "Choose a matching ZIP on this computer.",
  browserUploadDesktop: "Upload from Desktop",
  browserDownloadHereHint: "This environment downloads directly.",
  browserDownloadHere: "Download in environment",
  browserTransferProgress: "{received} / {total} MB",
  browserInEnvironment: "In this running environment",
  browserOnce: "One-time download for this version",
  browserDiskSize: "{size} MB on disk",
  browserDownloadSize: "{size} MB download",
  browserSource: "Get the browser",
  browserCancelled: "Cancelled",
  browserInstallFailed: "Installation failed. Check the connection or choose another source.",
  browserInstalling: "Installing…",
  browserVerifying: "Verifying package…",
  browserUploading: "Uploading…",
  browserDownloading: "Downloading…",
  browserNotInstalled: "Not installed",
  browserInstalled: "Installed",
  browserDisabledHint: "No use or installation prompts. Saved data stays here.",
  browserEnabledHint: "Ask before the first installation.",
  browserEnable: "Allow built-in browser",
  profileIsolationHint: "Groups keep website sign-ins separate. New groups start signed out.",
  profileDefault: "Shared website data",
  managedModeValue: "Headless, in this environment. No desktop window.",
  backToChat: "Back to conversation",
  environmentTitle: 'Running environment',
  environmentCapabilities: 'Browsers and desktop in this environment',
  scope: 'Current conversation only',
  confirmTarget: 'Use selection',
  cancel: 'Cancel',
  back: 'Back',
  unknown: 'Unknown',
  checking: 'Checking availability…',
  loadFailed: 'Unable to read the environment status. Keep it running and check again.',
  currentMissing: "The previous page or app is unavailable",
  currentMissingHint: "Continue your task in chat. Flower will find an available page or app.",
  selectionFailed: "Unable to confirm the selection. Refresh the list to check which page or window this conversation uses.",
  accessSettingsFailed: "Unable to load or save conversation permissions. Check the environment and try again.",
  selectionScope: 'Only this conversation. The task will not start.',
  allTargets: 'All',
  targetPages: 'Pages',
  targetApps: 'Apps',
  currentTarget: 'Current',
  noMatchingTargets: 'No matching pages or apps.',
  managedHint: "Headless browser for web tasks. Installation requires your confirmation.",
  managedMissingHint: "Built-in Chromium is unavailable. Check the installation details.",
  chromeTitle: 'Chrome in this environment',
  chromeOffline: 'No online Chrome detected',
  chromeOfflineHint: "No Chrome is online. Ordinary web tasks can use the built-in headless browser.",
  chromeOnlineHint: "Reuses tabs and website sign-ins from Chrome in this environment.",
  setupChrome: 'Set up or add Chrome',
  pairingSaved: 'Chrome is connected. Pairing is saved for automatic reconnection.',
  pairingConfirmHint: 'On the page that opens in Chrome, click Connect to confirm pairing. This will not change the page selected for this conversation.',
  pairingPersistence: 'After confirmation, the extension saves pairing and automatic-reconnection consent in this Chrome profile. Disconnect in the extension to turn off automatic reconnection. Pairing does not grant website access.',
  desktopTitle: 'Desktop and applications',
  desktopHint: "Works with application windows in this environment.",
  desktopMissingHint: 'The desktop helper or private desktop components are unavailable in this environment.',
  desktopPermissionHint: 'On this Mac, enable Screen Recording and Accessibility for Redeven in System Settings, then check again.',
  onDemand: 'Starts when needed',
  available: 'Available',
  stopped: 'Stopped',
  details: 'View details',
  manage: 'Manage',
  diagnostics: 'Environment diagnostics',
  repairHint: "Required components are missing from this environment’s Redeven installation.",
  permissionBoundary: 'Conversation permissions are saved separately. Full access does not install browser components, start a desktop, or enable operating-system permissions.',
  permissions: 'Conversation permissions',
  editPermissions: 'Change approval mode',
  help: "What is saved?",
  selectionPersistence: "Flower finds pages for each task. If a previous page closes, it can select a new one.",
  profileHint: "Website sign-ins persist here, separately from your Chrome data.",
  createProfileHint: "Separate website accounts (optional)",
  profileFailed: "Unable to read or save browser data. Try again.",
  advancedHint: 'Enter a Chromium debugging endpoint reachable from this environment. Discovered pages use the same selection flow; discovery does not replace the current page.',
  endpointFailed: 'Unable to discover pages at this debugging endpoint. Check the address and browser service, then try again.',
  noThread: 'Environment settings apply here. Open a conversation to choose its page or application and manage its permissions.',
  invalidOrigin: 'Enter a website origin such as https://example.com, without a path, query, or credentials.',
  managed: "Built-in headless browser",
  system: "Connected system browser",
  connectionTitle: "Connect Chrome",
  connectionHint: "Connect Chrome to continue this task automatically.",
  noFrame: "No screenshot available",
  frameConnecting: "Connecting to the view…",
  frameLoading: "Loading the view…",
  frameLoadingHint: "The view will appear here when it’s ready.",
  frameDisconnected: "View connection interrupted",
  frameStale: "Last captured view · not live",
  reveal: "View in browser",
  revealFailed: "Unable to show the browser tab. Check that the browser is connected.",
  profileName: "Group name, e.g. Work",
  createProfile: "Create group",
  extensionHint: "Install the Redeven Flower extension once to let Flower use Chrome.",
  setupUpdateTitle: "Update extension",
  setupUpdateHint: "The installed extension is out of date. Load the folder shown here again to update it.",
  setupAlreadyInstalled: "Already installed",
  setupInstalled: "Installed, continue",
  setupBack: "Back",
  setupHelp: "Need help?",
  setupHostHint: "Use Google Chrome on the computer running this environment. Safari and other browsers are not supported yet.",
  setupDeveloperMode: "Turn on Developer mode in the top right.",
  setupLoadUnpacked: "Click Load unpacked in the top left.",
  setupChooseFolder: "In the folder picker, follow the path above, select the extension folder and confirm.",
  setupHome: "Home",
  setupFolderHint: "Keep this folder in place after installation.",
  setupDragFolderHint: "Click Show folder, then drag the entire folder shown below onto Chrome’s Extensions page.",
  setupManualInstall: "Or install by selecting the folder",
  setupInstallDone: "When Redeven Flower appears in Chrome, choose Installed, continue below.",
  setupLabelsHint: "Button names may differ with Chrome’s language or version. In English, look for Developer mode and Load unpacked.",
  setupPreparing: 'Preparing the connection…',
  setupConfirming: 'Waiting for your confirmation in Chrome…',
  setupConnected: 'Chrome connected · continuing…',
  setupFailed: 'Unable to check the connection. Keep this environment running, then try again.',
  setupTimeout: 'No connection detected yet. Finish the steps in Chrome, then check again.',
  setupInstallTitle: "Install extension",
  setupConfirmTitle: "Connect Chrome",
  setupConfirmHint: "On the page that opens in Chrome, click Connect. Your task will continue automatically.",
  openExtensions: "Open Chrome extensions",
  openExtensionFolder: 'Show folder',
  copyExtensionPath: 'Copy folder path',
  pathCopied: 'Path copied',
  openConnection: "Connect in Chrome",
  setupOpenFailed: 'Unable to open Chrome or the folder. Make sure Google Chrome is installed on the computer running this environment and try again. Remote environments open it on that computer.',
  retryConnection: 'Check connection again',
  extensionPath: 'Extension folder',
  newTab: 'New background tab',
  title: 'Browser and desktop',
  target: "Pages and apps",
  automatic: "Flower chooses pages for your task",
  automaticHint: "Describe what you need in chat. Manual page selection is optional.",
  switchTarget: "Choose page or app manually",
  searchTargets: 'Search pages and applications',
  browserPages: 'Browser pages',
  applicationWindows: 'Application windows',
  inUse: 'Used by another task',
  disconnected: 'Not connected',
  selectionStale: 'This page or window changed. Refresh the list and choose it again.',
  refresh: 'Refresh',
  noTargets: 'No computer targets are available.',
  setupRequired: 'Setup required',
  permissionRequired: 'System permission required',
  sites: 'Allowed sites',
  sitePlaceholder: 'https://example.com',
  add: 'Add',
  remove: 'Remove access',
  apps: 'Allowed applications',
  foreground: 'Allow temporary desktop use',
  foregroundHint: 'Flower may bring an application forward to complete your task. Use Stop in Flower when you want to take control.',
  save: 'Save access',
  saved: 'Access saved',
  close: 'Close',
  listTabs: 'Find tabs',
  connected: 'Connected',
  advanced: 'Discover a self-managed Chromium browser',
  endpoint: 'Browser debugging endpoint',
  background: 'Running in background',
  usingDesktop: 'Using the desktop',
  waitingControl: 'Waiting for you',
  requestedAccess: 'Access needed to continue',
  grantRequested: 'Add requested access',
  revokeAll: 'Revoke all access',
  allowContinue: 'Allow and continue',
  fullAccessTitle: 'Full access is enabled',
  fullAccessHint: 'Websites, applications, and temporary desktop use are already allowed for this conversation. Choose Approval required in conversation settings to request confirmation.',
  authorizedHint: 'This paused step is already authorized by full access. Continue the task; Flower will check the page before resuming.',
  continueTask: 'Continue task',
  accessFailed: 'Access could not be saved. Try again; Flower has not continued.',
  accessTitle: 'Allow task access',
  siteTitle: 'Allow website access',
  accessHint: 'Flower needs the access listed below for this conversation. Allow it to continue automatically; no manual browser operation is needed.',
  targetTitle: 'Continue the browser task',
  targetHint: 'Continue the task. Flower will discover the available pages and choose the next page for you.',
  loginTitle: 'Sign in on the page',
  loginHint: 'Open the page and finish signing in. Enter passwords there, not in this conversation. Then choose Done, continue.',
  verificationTitle: 'Enter the verification code',
  verificationHint: 'Open the page and enter the one-time code there. Do not send the code in this conversation. Then choose Done, continue.',
  captchaTitle: 'Complete the CAPTCHA',
  captchaHint: 'Open the page and complete its human verification challenge. Then choose Done, continue; Flower will check the page before resuming.',
  privateTitle: 'Complete the private input',
  privateHint: 'Open the page and finish the password or verification field there. Private input stays out of the conversation. Then choose Done, continue.',
  inspectionTitle: 'Check the current page',
  inspectionHint: 'Flower could not safely inspect the page. Open it to check its state; a sign-in requirement has not been confirmed. Then choose Done, continue to check again.',
  untrustedTitle: 'Review unexpected page instructions',
  untrustedHint: 'The page contains instructions aimed at the agent. Open the page and leave or dismiss that content before continuing.',
  pausedTitle: 'Actions are paused',
  pausedHint: 'Finish your changes on the page or application, then choose Done, continue when Flower may resume.',
};
export type FlowerComputerCopy = { readonly [Key in keyof typeof computerUseEnUS]: string };
export function localizedComputerCopy(t: (key: string) => string): FlowerComputerCopy {
  return Object.fromEntries(Object.keys(computerUseEnUS).map(key => [key, t(`flowerSurface.computer.${key}`)])) as FlowerComputerCopy;
}
