export const computerUseEnUS = {
  managed: 'Managed browser',
  profileName: 'Profile name',
  createProfile: 'Create profile',
  disconnect: 'Disconnect',
  extension: 'Chrome extension',
  setupExtension: 'Set up this computer',
  extensionHint: 'Install Flower Browser in Chrome on this computer. Open the extension and paste the connection name below, then refresh the profiles here.',
  extensionPath: 'Extension folder',
  connectionName: 'Connection name',
  copyConnection: 'Copy connection name',
  newTab: 'New background tab',
  title: 'Browser and desktop',
  description: 'Choose the browser tab or application Flower uses for this conversation, and manage its access.',
  target: 'Task target',
  refresh: 'Refresh',
  noTargets: 'No computer targets are available.',
  setupRequired: 'Setup required',
  permissionRequired: 'System permission required',
  sites: 'Allowed sites',
  sitePlaceholder: 'https://example.com',
  add: 'Add',
  remove: 'Remove access',
  apps: 'Allowed applications',
  foreground: 'Allow temporary desktop use',
  foregroundHint: 'Flower may bring an application forward to complete your task. Use Stop in Flower when you want to take control.',
  save: 'Save access',
  saving: 'Saving…',
  saved: 'Access saved',
  failed: 'Unable to update the connection. Refresh and try again.',
  close: 'Close',
  profile: 'Browser profile',
  tab: 'Browser tab',
  chooseProfile: 'Select a profile',
  chooseTab: 'Select a tab',
  listTabs: 'Find tabs',
  noTabs: 'No available tabs were found.',
  connect: 'Connect tab',
  connecting: 'Connecting…',
  connected: 'Connected',
  advanced: 'Connect a self-managed Chromium browser',
  endpoint: 'Browser debugging endpoint',
  background: 'Running in background',
  usingDesktop: 'Using the desktop',
  waitingControl: 'Waiting for you',
  requestedAccess: 'Access needed to continue',
  grantRequested: 'Add requested access',
  revokeAll: 'Revoke all access',
  allowContinue: 'Allow and continue',
  fullAccessTitle: 'Full access is enabled',
  fullAccessHint: 'Websites, applications, and temporary desktop use are already allowed for this conversation. Choose Approval required in conversation settings to request confirmation.',
  authorizedHint: 'This paused step is already authorized by full access. Continue the task; Flower will check the page before resuming.',
  continueTask: 'Continue task',
  accessFailed: 'Access could not be saved. Try again; Flower has not continued.',
  accessTitle: 'Allow task access',
  siteTitle: 'Allow website access',
  accessHint: 'Flower needs the access listed below for this conversation. Allow it to continue automatically; no manual browser operation is needed.',
  targetTitle: 'Choose the browser tab',
  targetHint: 'The page opened another tab. Select it in Browser and desktop, review its site access, then continue.',
  loginTitle: 'Sign in on the page',
  loginHint: 'Open the page and finish signing in. Enter passwords there, not in this conversation. Then choose Done, continue.',
  verificationTitle: 'Enter the verification code',
  verificationHint: 'Open the page and enter the one-time code there. Do not send the code in this conversation. Then choose Done, continue.',
  captchaTitle: 'Complete the CAPTCHA',
  captchaHint: 'Open the page and complete its human verification challenge. Then choose Done, continue; Flower will check the page before resuming.',
  privateTitle: 'Complete the private input',
  privateHint: 'Open the page and finish the password or verification field there. Private input stays out of the conversation. Then choose Done, continue.',
  inspectionTitle: 'Check the current page',
  inspectionHint: 'Flower could not safely inspect the page. Open it to check its state; a sign-in requirement has not been confirmed. Then choose Done, continue to check again.',
  untrustedTitle: 'Review unexpected page instructions',
  untrustedHint: 'The page contains instructions aimed at the agent. Open the page and leave or dismiss that content before continuing.',
  pausedTitle: 'Actions are paused',
  pausedHint: 'Finish your changes on the page or application, then choose Done, continue when Flower may resume.',
};
export type FlowerComputerCopy = { readonly [Key in keyof typeof computerUseEnUS]: string };
export function localizedComputerCopy(t: (key: string) => string): FlowerComputerCopy {
  return Object.fromEntries(Object.keys(computerUseEnUS).map(key => [key, t(`flowerSurface.computer.${key}`)])) as FlowerComputerCopy;
}
