export const toolActivityEnUS = {
  "copy": "Copy",
  "inputs": "Input",
  "results": "Result",
  "noOutput": "No output",
  "detailsUnavailable": "This record did not save result details.",
  "inputUnavailable": "This record did not save the script.",
  "screenshotUnavailable": "This record did not save a screenshot.",
  "partialOutput": "Partial output — the operation did not complete.",
  "truncated": "Output truncated",
  "showAll": "Show all",
  "showLess": "Show less",
  "copyFailed": "Could not copy. Try again.",
  "execute": "Run script",
  "observe": "Inspect page or window",
  "screenshot": "Take screenshot",
  "click": "Click",
  "doubleClick": "Double-click",
  "type": "Enter text",
  "key": "Press key",
  "scroll": "Scroll",
  "drag": "Drag",
  "wait": "Wait",
  "navigate": "Open page",
  "back": "Go back",
  "reload": "Reload page",
  "read": "Read",
  "readFiles": "Read files",
  "edit": "Edit",
  "delete": "Delete",
  "searchFiles": "Search file contents",
  "findFiles": "Find files",
  "skill": "Load skill",
  "knowledgeIndex": "Browse knowledge",
  "knowledgeSearch": "Search knowledge",
  "knowledgeOpen": "Read knowledge",
  "called": "Run tool",
  "question": "Ask a question",
  "todos": "Update todos",
  "sources": "View sources",
  "fetch": "Fetch page",
  "patch": "Apply changes",
  "inputQuery": "Search terms",
  "inputPaths": "Files and folders",
  "inputName": "Name",
  "inputLimit": "Result limit",
  "inputGlob": "Filename pattern",
  "inputContext": "Context lines",
  "inputDepth": "Search depth",
  "inputType": "Type",
  "inputTags": "Tags",
  "inputSection": "Section",
  "inputEvidence": "Include evidence",
  "inputOffset": "Start position",
  "inputReason": "Reason",
  "inputScreenshot": "Include screenshot",
  "inputKey": "Key",
  "inputURL": "URL",
  "inputX": "X coordinate",
  "inputY": "Y coordinate",
  "inputDeltaX": "Horizontal scroll",
  "inputDeltaY": "Vertical scroll",
  "inputFromX": "Start X",
  "inputFromY": "Start Y",
  "inputToX": "End X",
  "inputToY": "End Y",
  "inputDuration": "Duration (ms)",
  "summary": "Summary",
  "files": "files",
  "fileCount": "{count} files",
  "file": "file",
  "fileActions": "File actions",
  "previewFile": "Preview file",
  "browseFolder": "Browse folder"
} as const;

export type FlowerToolActivityCopy = Readonly<Record<keyof typeof toolActivityEnUS, string>>;
