import type { ManagedCatalogTemplate } from './EnvPortForwardsPage';

export const template: ManagedCatalogTemplate = {
  template_id: 'git_example',
  name: 'Example',
  description: 'Example service',
  source: 'git',
  default_locale: 'en-US',
  deployment: 'host',
  revision: 1,
  available: true,
  editable: false,
  duplicateable: false,
  developer_preview: false,
  disk_bytes: 0,
  data_location: '',
  source_url: '',
  docker_source_url: '',
  service_family_id: 'git_family',
  deployments: [],
  default_workspace_path: '/workspace/example',
  workspace_roots: [],
  git_source: {
    repository: 'owner/repo',
    repository_id: 1,
    ref: 'develop',
    path: '',
    commit_sha: 'a'.repeat(40),
    sha256: 'b'.repeat(64),
    document_template_id: 'example',
    document_family_id: 'example',
  },
  spec: { schema_version: 6, kind: 'host', endpoint: { scheme: 'http' }, host: { start_script: 'exec app' } },
};
