package redevpluginintegration

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	redevpluginartifacts "github.com/floegence/redeven/spec/redevplugin"
	"github.com/floegence/redevplugin/pkg/capabilitycontract"
	"github.com/floegence/redevplugin/pkg/manifest"
	"github.com/floegence/redevplugin/pkg/pluginpkg"
	"github.com/floegence/redevplugin/pkg/version"
)

const developmentDeliverySchemaVersion = "redeven.plugin_development_delivery.v3"
const officialContainersPluginInstanceID = "plugini_redeven_official_containers"
const officialContainersReleaseNotesID = "containers-4.0.0"
const officialContainersSourceRepository = "https://github.com/floegence/redeven-official-plugins.git"
const officialContainersSourceCommit = "b9eb04f6cc08eab35e0d0a8a5ac671ec5077aaed"

type developmentDeliveryDescriptor struct {
	SchemaVersion          string `json:"schema_version"`
	PluginInstanceID       string `json:"plugin_instance_id"`
	PublisherID            string `json:"publisher_id"`
	PluginID               string `json:"plugin_id"`
	Version                string `json:"version"`
	PackagePath            string `json:"package_path"`
	PackageSHA256          string `json:"package_sha256"`
	ReleaseNotesID         string `json:"release_notes_id"`
	ReleaseNotesSummarySHA string `json:"release_notes_summary_sha256"`
	SourceRepository       string `json:"source_repository"`
	SourceCommit           string `json:"source_commit"`
}

// DevelopmentDelivery is a validated, read-only projection of the one
// package generated by dev_desktop.sh. It is never used by production builds.
type DevelopmentDelivery struct {
	descriptor   developmentDeliveryDescriptor
	packageData  []byte
	contract     capabilitycontract.VerifiedContract
	packageHash  string
	manifestHash string
	entriesHash  string
}

func (d *DevelopmentDelivery) PackageBytes() []byte {
	if d == nil {
		return nil
	}
	return append([]byte(nil), d.packageData...)
}

func (d *DevelopmentDelivery) Metadata() map[string]any {
	if d == nil {
		return nil
	}
	return map[string]any{
		"plugin_instance_id":           d.descriptor.PluginInstanceID,
		"plugin_id":                    d.descriptor.PluginID,
		"publisher_id":                 d.descriptor.PublisherID,
		"version":                      d.descriptor.Version,
		"package_url":                  "/_redeven_proxy/api/plugins/development-delivery/containers/package",
		"package_sha256":               d.descriptor.PackageSHA256,
		"package_hash":                 d.packageHash,
		"manifest_hash":                d.manifestHash,
		"entries_hash":                 d.entriesHash,
		"capability_version":           d.contract.Contract.CapabilityVersion,
		"release_notes_id":             d.descriptor.ReleaseNotesID,
		"release_notes_summary_sha256": d.descriptor.ReleaseNotesSummarySHA,
		"source_repository":            d.descriptor.SourceRepository,
		"source_commit":                d.descriptor.SourceCommit,
		"development_only":             true,
	}
}

func loadDevelopmentDelivery(filename string) (*DevelopmentDelivery, error) {
	filename = strings.TrimSpace(filename)
	if filename == "" {
		return nil, nil
	}
	var descriptor developmentDeliveryDescriptor
	if err := readStrictDevelopmentJSON(filename, &descriptor); err != nil {
		return nil, fmt.Errorf("read plugin development delivery: %w", err)
	}
	if descriptor.SchemaVersion != developmentDeliverySchemaVersion ||
		descriptor.PluginInstanceID != officialContainersPluginInstanceID ||
		descriptor.PublisherID != officialPublisherID ||
		descriptor.PluginID != officialContainersPluginID || descriptor.Version != "4.0.0" {
		return nil, errors.New("plugin development delivery identity is invalid")
	}
	if descriptor.ReleaseNotesID != officialContainersReleaseNotesID || !isSHA256Hex(descriptor.ReleaseNotesSummarySHA) {
		return nil, errors.New("plugin development delivery release notes binding is invalid")
	}
	if descriptor.SourceRepository != officialContainersSourceRepository || descriptor.SourceCommit != officialContainersSourceCommit {
		return nil, errors.New("plugin development delivery source identity is invalid")
	}
	if !filepath.IsAbs(descriptor.PackagePath) || strings.Contains(descriptor.PackagePath, ".."+string(os.PathSeparator)) {
		return nil, errors.New("plugin development delivery package_path must be absolute")
	}
	packageData, err := os.ReadFile(filepath.Clean(descriptor.PackagePath))
	if err != nil {
		return nil, fmt.Errorf("read development plugin package: %w", err)
	}
	if !matchesSHA256(packageData, descriptor.PackageSHA256) {
		return nil, errors.New("development plugin package hash does not match descriptor")
	}
	bundle, trustedKey, err := redevpluginartifacts.ContainersCapabilityBundle()
	if err != nil {
		return nil, fmt.Errorf("load signed production capability: %w", err)
	}
	verified, err := capabilitycontract.Verify(capabilitycontract.VerifyRequest{
		Bundle:                    bundle,
		ExpectedPin:               bundle.Pin,
		TrustedKey:                trustedKey,
		CurrentReDevPluginVersion: version.CurrentCompatibilityVersion(),
	})
	if err != nil {
		return nil, fmt.Errorf("verify signed production capability: %w", err)
	}
	if verified.Contract.ContractID != "redeven.container_resources.v4" || verified.Contract.ContractVersion != "4.0.0" ||
		verified.Contract.CapabilityID != containersCapabilityID || verified.Contract.CapabilityVersion != containersCapabilityV4Version || len(verified.Contract.Methods) != 52 {
		return nil, errors.New("development capability contract identity is invalid")
	}
	pkg, err := pluginpkg.Read(context.Background(), bytes.NewReader(packageData), int64(len(packageData)), pluginpkg.DefaultReadLimits())
	if err != nil {
		return nil, fmt.Errorf("read development plugin package: %w", err)
	}
	if pkg.Manifest.PluginID() != descriptor.PluginID || pkg.Manifest.Version() != descriptor.Version || len(pkg.Manifest.CapabilityBindings) != 1 ||
		pkg.Manifest.CapabilityBindings[0].BindingID != "containers-v4" || pkg.Manifest.CapabilityBindings[0].Contract != bundle.Pin ||
		!developmentMethodRoutesMatch(pkg.Manifest.Methods, verified.Contract.Methods) {
		return nil, errors.New("development plugin package does not bind the signed production contract")
	}
	return &DevelopmentDelivery{
		descriptor: descriptor, packageData: packageData, contract: verified,
		packageHash: pkg.PackageHash, manifestHash: pkg.ManifestHash, entriesHash: pkg.EntriesHash,
	}, nil
}

func developmentMethodRoutesMatch(routes []manifest.MethodSpec, methods []capabilitycontract.Method) bool {
	if len(routes) != len(methods) {
		return false
	}
	expected := make(map[string]struct{}, len(methods))
	for _, method := range methods {
		expected[method.Name] = struct{}{}
	}
	for _, route := range routes {
		if _, ok := expected[route.Method]; !ok || route.Route.Kind != manifest.MethodRouteCapability ||
			route.Route.BindingID != "containers-v4" || route.Route.TargetMethod != route.Method {
			return false
		}
		delete(expected, route.Method)
	}
	return len(expected) == 0
}

func readStrictDevelopmentJSON(filename string, target any) error {
	data, err := os.ReadFile(filename)
	if err != nil {
		return err
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return err
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("trailing JSON data")
		}
		return err
	}
	return nil
}

func matchesSHA256(data []byte, expected string) bool {
	digest := sha256.Sum256(data)
	got := hex.EncodeToString(digest[:])
	expected = strings.TrimPrefix(strings.TrimSpace(expected), "sha256:")
	return len(expected) == 64 && strings.EqualFold(got, expected)
}

func isSHA256Hex(value string) bool {
	value = strings.TrimPrefix(strings.TrimSpace(value), "sha256:")
	if len(value) != 64 {
		return false
	}
	_, err := hex.DecodeString(value)
	return err == nil
}
