package redevpluginintegration

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/floegence/redevplugin/pkg/capabilitycontract"
	"github.com/floegence/redevplugin/pkg/manifest"
	"github.com/floegence/redevplugin/pkg/pluginpkg"
	"github.com/floegence/redevplugin/pkg/version"
)

const developmentDeliverySchemaVersion = "redeven.plugin_development_delivery.v1"
const officialContainersPluginInstanceID = "plugini_redeven_official_containers"

type developmentDeliveryDescriptor struct {
	SchemaVersion           string `json:"schema_version"`
	PluginInstanceID        string `json:"plugin_instance_id"`
	PublisherID             string `json:"publisher_id"`
	PluginID                string `json:"plugin_id"`
	Version                 string `json:"version"`
	PackagePath             string `json:"package_path"`
	PackageSHA256           string `json:"package_sha256"`
	CapabilityRoot          string `json:"capability_root"`
	CapabilityPinPath       string `json:"capability_pin_path"`
	CapabilityPublicKeyPath string `json:"capability_public_key_path"`
	ContractSHA256          string `json:"contract_sha256"`
}

type developmentSigningPublicKey struct {
	SchemaVersion string `json:"schema_version"`
	Algorithm     string `json:"algorithm"`
	KeyID         string `json:"key_id"`
	PublicKey     string `json:"public_key"`
	CreatedAt     string `json:"created_at"`
}

// DevelopmentDelivery is an authenticated, read-only projection of the one
// package generated by dev_desktop.sh. It is never used by production builds.
type DevelopmentDelivery struct {
	descriptor   developmentDeliveryDescriptor
	packageData  []byte
	contract     capabilitycontract.VerifiedContract
	packageHash  string
	manifestHash string
	entriesHash  string
}

func (d *DevelopmentDelivery) PackageBytes() []byte {
	if d == nil {
		return nil
	}
	return append([]byte(nil), d.packageData...)
}

func (d *DevelopmentDelivery) Metadata() map[string]any {
	if d == nil {
		return nil
	}
	return map[string]any{
		"plugin_instance_id": d.descriptor.PluginInstanceID,
		"plugin_id":          d.descriptor.PluginID,
		"publisher_id":       d.descriptor.PublisherID,
		"version":            d.descriptor.Version,
		"package_url":        "/_redeven_proxy/api/plugins/development-delivery/containers/package",
		"package_sha256":     d.descriptor.PackageSHA256,
		"package_hash":       d.packageHash,
		"manifest_hash":      d.manifestHash,
		"entries_hash":       d.entriesHash,
		"capability_version": d.contract.Contract.CapabilityVersion,
		"development_only":   true,
	}
}

func loadDevelopmentDelivery(filename string) (*DevelopmentDelivery, error) {
	filename = strings.TrimSpace(filename)
	if filename == "" {
		return nil, nil
	}
	var descriptor developmentDeliveryDescriptor
	if err := readStrictDevelopmentJSON(filename, &descriptor); err != nil {
		return nil, fmt.Errorf("read plugin development delivery: %w", err)
	}
	if descriptor.SchemaVersion != developmentDeliverySchemaVersion ||
		descriptor.PluginInstanceID != officialContainersPluginInstanceID ||
		descriptor.PublisherID != officialPublisherID ||
		descriptor.PluginID != officialContainersPluginID || descriptor.Version != "4.0.0" {
		return nil, errors.New("plugin development delivery identity is invalid")
	}
	for name, value := range map[string]string{
		"package_path":               descriptor.PackagePath,
		"capability_root":            descriptor.CapabilityRoot,
		"capability_pin_path":        descriptor.CapabilityPinPath,
		"capability_public_key_path": descriptor.CapabilityPublicKeyPath,
	} {
		if !filepath.IsAbs(value) || strings.Contains(value, ".."+string(os.PathSeparator)) {
			return nil, fmt.Errorf("plugin development delivery %s must be absolute", name)
		}
	}
	packageData, err := os.ReadFile(filepath.Clean(descriptor.PackagePath))
	if err != nil {
		return nil, fmt.Errorf("read development plugin package: %w", err)
	}
	if !matchesSHA256(packageData, descriptor.PackageSHA256) {
		return nil, errors.New("development plugin package hash does not match descriptor")
	}
	var pin capabilitycontract.Pin
	if err := readStrictDevelopmentJSON(descriptor.CapabilityPinPath, &pin); err != nil {
		return nil, fmt.Errorf("read development capability pin: %w", err)
	}
	if err := capabilitycontract.ValidatePin(pin); err != nil {
		return nil, fmt.Errorf("development capability pin is invalid: %w", err)
	}
	var public developmentSigningPublicKey
	if err := readStrictDevelopmentJSON(descriptor.CapabilityPublicKeyPath, &public); err != nil {
		return nil, fmt.Errorf("read development capability public key: %w", err)
	}
	publicKey, err := base64.StdEncoding.DecodeString(public.PublicKey)
	if err != nil {
		return nil, fmt.Errorf("decode development capability public key: %w", err)
	}
	if public.SchemaVersion != "redevplugin.ed25519_signing_key.v1" || public.Algorithm != "ed25519" ||
		public.KeyID != pin.SignatureKeyID || len(publicKey) != 32 {
		return nil, errors.New("development capability public key identity is invalid")
	}
	bundle := capabilitycontract.Bundle{Pin: pin, Files: make(map[string][]byte, 6)}
	for _, ref := range []string{pin.ArtifactRef, pin.ManifestRef, pin.SignatureRef, pin.CompatibilityRef, pin.GeneratedClientRef, pin.NoticesRef} {
		content, err := os.ReadFile(filepath.Join(descriptor.CapabilityRoot, filepath.FromSlash(ref)))
		if err != nil {
			return nil, fmt.Errorf("read development capability artifact %s: %w", ref, err)
		}
		bundle.Files[ref] = content
	}
	verified, err := capabilitycontract.Verify(capabilitycontract.VerifyRequest{
		Bundle: bundle, ExpectedPin: pin,
		TrustedKey: capabilitycontract.TrustedKey{
			PublisherID: pin.PublisherID, KeyID: pin.SignatureKeyID, PublicKey: publicKey,
			PolicyEpoch: pin.SignaturePolicyEpoch, RevocationEpoch: pin.SignatureRevocationEpoch,
		},
		CurrentReDevPluginVersion: version.CurrentCompatibilityVersion(),
	})
	if err != nil {
		return nil, fmt.Errorf("verify development capability artifacts: %w", err)
	}
	if verified.Contract.ContractID != "redeven.container_resources.v4" || verified.Contract.ContractVersion != "4.0.0" ||
		verified.Contract.CapabilityID != containersCapabilityID || verified.Contract.CapabilityVersion != containersCapabilityV4Version || len(verified.Contract.Methods) != 52 {
		return nil, errors.New("development capability contract identity is invalid")
	}
	pkg, err := pluginpkg.Read(context.Background(), bytes.NewReader(packageData), int64(len(packageData)), pluginpkg.DefaultReadLimits())
	if err != nil {
		return nil, fmt.Errorf("read development plugin package: %w", err)
	}
	if pkg.Manifest.PluginID() != descriptor.PluginID || pkg.Manifest.Version() != descriptor.Version || len(pkg.Manifest.CapabilityBindings) != 1 ||
		pkg.Manifest.CapabilityBindings[0].BindingID != "containers-v4" || pkg.Manifest.CapabilityBindings[0].Contract != pin ||
		!developmentMethodRoutesMatch(pkg.Manifest.Methods, verified.Contract.Methods) {
		return nil, errors.New("development plugin package does not bind the verified capability")
	}
	if !matchesSHA256(bundle.Files[pin.ArtifactRef], descriptor.ContractSHA256) {
		return nil, errors.New("development capability contract hash does not match descriptor")
	}
	return &DevelopmentDelivery{
		descriptor: descriptor, packageData: packageData, contract: verified,
		packageHash: pkg.PackageHash, manifestHash: pkg.ManifestHash, entriesHash: pkg.EntriesHash,
	}, nil
}

func developmentMethodRoutesMatch(routes []manifest.MethodSpec, methods []capabilitycontract.Method) bool {
	if len(routes) != len(methods) {
		return false
	}
	expected := make(map[string]struct{}, len(methods))
	for _, method := range methods {
		expected[method.Name] = struct{}{}
	}
	for _, route := range routes {
		if _, ok := expected[route.Method]; !ok || route.Route.Kind != manifest.MethodRouteCapability ||
			route.Route.BindingID != "containers-v4" || route.Route.TargetMethod != route.Method {
			return false
		}
		delete(expected, route.Method)
	}
	return len(expected) == 0
}

func readStrictDevelopmentJSON(filename string, target any) error {
	data, err := os.ReadFile(filename)
	if err != nil {
		return err
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return err
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("trailing JSON data")
		}
		return err
	}
	return nil
}

func matchesSHA256(data []byte, expected string) bool {
	digest := sha256.Sum256(data)
	got := hex.EncodeToString(digest[:])
	expected = strings.TrimPrefix(strings.TrimSpace(expected), "sha256:")
	return len(expected) == 64 && strings.EqualFold(got, expected)
}
