// Explicit popup catalogs. Browser profile names remain user content.
export const messages = {
  'en-US': { intro: 'Use the connection name from Flower on this computer, then choose a tab in Flower.', profile: 'Profile name', bridge: 'Flower connection', connect: 'Connect', disconnect: 'Disconnect', connected: 'Connected. Choose a tab in Flower.', disconnected: 'Not connected', failed: 'Connection unavailable. Check Flower on this computer.' },
  'zh-CN': { intro: '输入这台电脑上 Flower 提供的连接名称，然后在 Flower 中选择标签页。', profile: '配置文件名称', bridge: 'Flower 连接', connect: '连接', disconnect: '断开', connected: '已连接，请在 Flower 中选择标签页。', disconnected: '未连接', failed: '连接不可用，请检查这台电脑上的 Flower。' },
  'zh-TW': { intro: '輸入這台電腦上 Flower 提供的連線名稱，然後在 Flower 中選擇分頁。', profile: '設定檔名稱', bridge: 'Flower 連線', connect: '連線', disconnect: '中斷連線', connected: '已連線，請在 Flower 中選擇分頁。', disconnected: '未連線', failed: '連線無法使用，請檢查這台電腦上的 Flower。' },
  'ja-JP': { intro: 'このコンピューターの Flower に表示された接続名を入力し、Flower でタブを選択します。', profile: 'プロファイル名', bridge: 'Flower の接続', connect: '接続', disconnect: '切断', connected: '接続済み。Flower でタブを選択してください。', disconnected: '未接続', failed: '接続できません。このコンピューターの Flower を確認してください。' },
  'ko-KR': { intro: '이 컴퓨터의 Flower에 표시된 연결 이름을 입력한 다음 Flower에서 탭을 선택하세요.', profile: '프로필 이름', bridge: 'Flower 연결', connect: '연결', disconnect: '연결 해제', connected: '연결되었습니다. Flower에서 탭을 선택하세요.', disconnected: '연결되지 않음', failed: '연결할 수 없습니다. 이 컴퓨터의 Flower를 확인하세요.' },
  'fr-FR': { intro: 'Saisissez le nom de connexion fourni par Flower sur cet ordinateur, puis choisissez un onglet dans Flower.', profile: 'Nom du profil', bridge: 'Connexion Flower', connect: 'Connecter', disconnect: 'Déconnecter', connected: 'Connecté. Choisissez un onglet dans Flower.', disconnected: 'Non connecté', failed: 'Connexion indisponible. Vérifiez Flower sur cet ordinateur.' },
  'de-DE': { intro: 'Geben Sie den Verbindungsnamen aus Flower auf diesem Computer ein und wählen Sie dann einen Tab in Flower.', profile: 'Profilname', bridge: 'Flower-Verbindung', connect: 'Verbinden', disconnect: 'Trennen', connected: 'Verbunden. Wählen Sie einen Tab in Flower.', disconnected: 'Nicht verbunden', failed: 'Verbindung nicht verfügbar. Prüfen Sie Flower auf diesem Computer.' },
  'es-ES': { intro: 'Introduce el nombre de conexión que muestra Flower en este ordenador y elige una pestaña en Flower.', profile: 'Nombre del perfil', bridge: 'Conexión de Flower', connect: 'Conectar', disconnect: 'Desconectar', connected: 'Conectado. Elige una pestaña en Flower.', disconnected: 'Sin conexión', failed: 'Conexión no disponible. Comprueba Flower en este ordenador.' },
  'pt-BR': { intro: 'Insira o nome de conexão exibido pelo Flower neste computador e escolha uma aba no Flower.', profile: 'Nome do perfil', bridge: 'Conexão do Flower', connect: 'Conectar', disconnect: 'Desconectar', connected: 'Conectado. Escolha uma aba no Flower.', disconnected: 'Desconectado', failed: 'Conexão indisponível. Verifique o Flower neste computador.' },
  'ru-RU': { intro: 'Введите имя подключения из Flower на этом компьютере, затем выберите вкладку в Flower.', profile: 'Имя профиля', bridge: 'Подключение Flower', connect: 'Подключить', disconnect: 'Отключить', connected: 'Подключено. Выберите вкладку в Flower.', disconnected: 'Не подключено', failed: 'Подключение недоступно. Проверьте Flower на этом компьютере.' },
};
