export type ModelCatalogCopy = Readonly<{
  searchAvailable: string; searchUnsupported: string; searchNotIntegrated: string;
  searchNotConfigured: string; searchNeedsKey: string; searchEndpointUnsupported: string;
  searchPending: string; searchPartial: string;
  search: string; selected: string; selectAll: string; clearAll: string; refresh: string;
  loading: string; empty: string; preview: string; experimental: string;
  unavailable: string; edit: string; reset: string; optionalKey: string;
}>;

const messages: Record<string, readonly string[]> = {
  'en-US': ['Search models', '{count} selected', 'Select all', 'Clear selection', 'Refresh models', 'Loading models…', 'No matching models', 'Preview', 'Experimental', 'The current model is unavailable. Choose another model.', 'Edit model', 'Reset to defaults', "API key optional", "Web search", "Web search not supported", "Web search not integrated", "Web search not configured", "Search API key required", "Web search unavailable on this endpoint", "Search capability pending", "Web search available for some models"],
  'zh-CN': ['搜索模型', '已选 {count} 个', '全部勾选', '取消全部', '刷新模型', '正在加载模型…', '没有匹配的模型', '预览版', '实验版', '当前模型不可用，请重新选择模型。', '编辑模型', '恢复默认参数', "API 密钥可选", "联网搜索", "不支持联网搜索", "当前未接入联网搜索", "未配置联网搜索", "需要搜索 API 密钥", "此端点无法使用联网搜索", "搜索能力待确认", "部分模型支持联网搜索"],
  'zh-TW': ['搜尋模型', '已選 {count} 個', '全部勾選', '取消全部', '重新整理模型', '正在載入模型…', '沒有符合的模型', '預覽版', '實驗版', '目前模型無法使用，請重新選擇模型。', '編輯模型', '還原預設參數', "API 金鑰為選填", "聯網搜尋", "不支援聯網搜尋", "目前未整合聯網搜尋", "尚未設定聯網搜尋", "需要搜尋 API 金鑰", "此端點無法使用聯網搜尋", "搜尋能力待確認", "部分模型支援聯網搜尋"],
  'ja-JP': ['モデルを検索', '{count} 件選択中', 'すべて選択', '選択を解除', 'モデルを更新', 'モデルを読み込み中…', '一致するモデルがありません', 'プレビュー', '試験版', '現在のモデルは利用できません。別のモデルを選択してください。', 'モデルを編集', '既定値に戻す', "API キーは任意", "ウェブ検索", "ウェブ検索非対応", "ウェブ検索未連携", "ウェブ検索未設定", "検索 API キーが必要です", "このエンドポイントではウェブ検索を利用できません", "検索機能は未確認です", "一部のモデルでウェブ検索を利用可能"],
  'ko-KR': ['모델 검색', '{count}개 선택됨', '모두 선택', '선택 해제', '모델 새로고침', '모델 불러오는 중…', '일치하는 모델이 없습니다', '미리 보기', '실험 버전', '현재 모델을 사용할 수 없습니다. 다른 모델을 선택하세요.', '모델 편집', '기본값으로 재설정', "API 키 선택 사항", "웹 검색", "웹 검색 미지원", "웹 검색 미연동", "웹 검색 미설정", "검색 API 키 필요", "이 엔드포인트에서는 웹 검색을 사용할 수 없습니다", "검색 기능 확인 대기 중", "일부 모델에서 웹 검색 가능"],
  'de-DE': ['Modelle suchen', '{count} ausgewählt', 'Alle auswählen', 'Auswahl aufheben', 'Modelle aktualisieren', 'Modelle werden geladen…', 'Keine passenden Modelle', 'Vorschau', 'Experimentell', 'Das aktuelle Modell ist nicht verfügbar. Wählen Sie ein anderes Modell.', 'Modell bearbeiten', 'Standardwerte wiederherstellen', "API-Schlüssel optional", "Websuche", "Websuche nicht unterstützt", "Websuche nicht integriert", "Websuche nicht konfiguriert", "Such-API-Schlüssel erforderlich", "Websuche an diesem Endpunkt nicht verfügbar", "Modelle aktualisieren, um die Websuche zu prüfen", "Websuche für einige Modelle verfügbar"],
  'fr-FR': ['Rechercher des modèles', '{count} sélectionnés', 'Tout sélectionner', 'Effacer la sélection', 'Actualiser les modèles', 'Chargement des modèles…', 'Aucun modèle correspondant', 'Aperçu', 'Expérimental', 'Le modèle actuel est indisponible. Choisissez un autre modèle.', 'Modifier le modèle', 'Rétablir les paramètres par défaut', "Clé API facultative", "Recherche web", "Recherche web non prise en charge", "Recherche web non intégrée", "Recherche web non configurée", "Clé API de recherche requise", "Recherche web indisponible sur ce point de terminaison", "Recherche web en attente de vérification", "Recherche web disponible pour certains modèles"],
  'es-ES': ['Buscar modelos', '{count} seleccionados', 'Seleccionar todos', 'Borrar selección', 'Actualizar modelos', 'Cargando modelos…', 'No hay modelos coincidentes', 'Vista previa', 'Experimental', 'El modelo actual no está disponible. Elige otro modelo.', 'Editar modelo', 'Restablecer valores predeterminados', "Clave API opcional", "Búsqueda web", "Búsqueda web no compatible", "Búsqueda web no integrada", "Búsqueda web sin configurar", "Se requiere una clave API de búsqueda", "Búsqueda web no disponible en este endpoint", "Búsqueda web pendiente de verificación", "Búsqueda web disponible para algunos modelos"],
  'pt-BR': ['Buscar modelos', '{count} selecionados', 'Selecionar todos', 'Limpar seleção', 'Atualizar modelos', 'Carregando modelos…', 'Nenhum modelo correspondente', 'Prévia', 'Experimental', 'O modelo atual está indisponível. Escolha outro modelo.', 'Editar modelo', 'Restaurar padrões', "Chave de API opcional", "Pesquisa na web", "Pesquisa na web não suportada", "Pesquisa na web não integrada", "Pesquisa na web não configurada", "Chave de API de pesquisa necessária", "Pesquisa na web indisponível neste endpoint", "Pesquisa na web aguardando verificação", "Pesquisa na web disponível para alguns modelos"],
  'ru-RU': ['Поиск моделей', 'Выбрано: {count}', 'Выбрать все', 'Снять выделение', 'Обновить модели', 'Загрузка моделей…', 'Подходящих моделей нет', 'Предварительная версия', 'Экспериментальная', 'Текущая модель недоступна. Выберите другую модель.', 'Изменить модель', 'Восстановить настройки', "Ключ API необязателен", "Поиск в интернете", "Поиск в интернете не поддерживается", "Поиск в интернете не подключён", "Поиск в интернете не настроен", "Требуется API-ключ поиска", "Поиск недоступен на этой конечной точке", "Возможность поиска ещё не проверена", "Поиск доступен для некоторых моделей"],
};

export function modelCatalogCopy(locale: string): ModelCatalogCopy {
  const [search, selected, selectAll, clearAll, refresh, loading, empty, preview, experimental, unavailable, edit, reset, optionalKey, searchAvailable, searchUnsupported, searchNotIntegrated, searchNotConfigured, searchNeedsKey, searchEndpointUnsupported, searchPending, searchPartial] = messages[locale] ?? messages['en-US'];
  return { search, selected, selectAll, clearAll, refresh, loading, empty, preview, experimental, unavailable, edit, reset, optionalKey, searchAvailable, searchUnsupported, searchNotIntegrated, searchNotConfigured, searchNeedsKey, searchEndpointUnsupported, searchPending, searchPartial };
}
