export const FLOWER_PROVIDER_MODEL_NOTE_KEYS = [
  'openai_gpt_55_frontier',
  'openai_gpt_54_professional',
  'openai_gpt_54_mini',
  'openai_gpt_54_nano',
  'openai_gpt_52_previous_flagship',
  'openai_gpt_52_mini',
  'openai_gpt_5_stable',
  'openai_gpt_5_mini',
  'claude_opus_47_note',
  'anthropic_sonnet_46',
  'claude_haiku_45_note',
  'moonshot_kimi_k26',
  'chatglm_glm_51',
  'deepseek_v4_pro',
  'deepseek_v4_flash',
  'qwen36_plus',
  'qwen36_plus_snapshot',
  'qwen36_flash',
  'qwen36_flash_snapshot',
  'openrouter_dynamic_metadata',
  'xai_grok_43',
  'groq_qwen_reasoning',
  'groq_gpt_oss',
  'ollama_local_reasoning_metadata',
] as const;

export type FlowerProviderModelNoteKey = typeof FLOWER_PROVIDER_MODEL_NOTE_KEYS[number];

const EN_US_MODEL_NOTES: Readonly<Record<FlowerProviderModelNoteKey, string>> = {
  openai_gpt_55_frontier: 'Latest frontier model for complex reasoning and coding',
  openai_gpt_54_professional: 'Affordable frontier model for professional work',
  openai_gpt_54_mini: 'Fast, cost-effective GPT-5.4 variant',
  openai_gpt_54_nano: 'Low-cost option for simple high-volume tasks',
  openai_gpt_52_previous_flagship: 'Previous flagship model',
  openai_gpt_52_mini: 'Cost-effective flagship variant',
  openai_gpt_5_stable: 'Stable flagship',
  openai_gpt_5_mini: 'Stable lightweight option',
  claude_opus_47_note: 'Most capable Claude model for complex agentic coding',
  anthropic_sonnet_46: 'Best balance of speed and intelligence',
  claude_haiku_45_note: 'Fastest current Claude model',
  moonshot_kimi_k26: 'Current Kimi flagship with built-in web search',
  chatglm_glm_51: 'Current GLM flagship with built-in web search',
  deepseek_v4_pro: 'Current V4 flagship model',
  deepseek_v4_flash: 'Current V4 fast model',
  qwen36_plus: 'Current Qwen3.6 Plus with built-in web search',
  qwen36_plus_snapshot: 'Pinned Qwen3.6 Plus snapshot with built-in web search',
  qwen36_flash: 'Current Qwen3.6 Flash with built-in web search',
  qwen36_flash_snapshot: 'Pinned Qwen3.6 Flash snapshot with built-in web search',
  openrouter_dynamic_metadata: 'Uses OpenRouter model metadata for reasoning controls',
  xai_grok_43: 'xAI Grok model with official reasoning effort controls',
  groq_qwen_reasoning: 'Groq Qwen reasoning model with default/off reasoning',
  groq_gpt_oss: 'Groq GPT-OSS model with low, medium, and high reasoning',
  ollama_local_reasoning_metadata: 'Local Ollama model family with dynamic thinking support',
};

const ZH_CN_MODEL_NOTES: Readonly<Record<FlowerProviderModelNoteKey, string>> = {
  openai_gpt_55_frontier: '适合复杂推理和代码任务的最新前沿模型',
  openai_gpt_54_professional: '适合专业工作的高性价比前沿模型',
  openai_gpt_54_mini: '快速且成本友好的 GPT-5.4 变体',
  openai_gpt_54_nano: '适合简单高频任务的低成本选项',
  openai_gpt_52_previous_flagship: '上一代旗舰模型',
  openai_gpt_52_mini: '高性价比旗舰变体',
  openai_gpt_5_stable: '稳定版旗舰模型',
  openai_gpt_5_mini: '稳定轻量选项',
  claude_opus_47_note: '适合复杂自主编程任务的最强 Claude 模型',
  anthropic_sonnet_46: '速度与智能平衡最佳',
  claude_haiku_45_note: '当前最快的 Claude 模型',
  moonshot_kimi_k26: '内置网页搜索的当前 Kimi 旗舰模型',
  chatglm_glm_51: '内置网页搜索的当前 GLM 旗舰模型',
  deepseek_v4_pro: '当前 V4 旗舰模型',
  deepseek_v4_flash: '当前 V4 快速模型',
  qwen36_plus: '内置网页搜索的当前 Qwen3.6 Plus',
  qwen36_plus_snapshot: '内置网页搜索的 Qwen3.6 Plus 固定快照',
  qwen36_flash: '内置网页搜索的当前 Qwen3.6 Flash',
  qwen36_flash_snapshot: '内置网页搜索的 Qwen3.6 Flash 固定快照',
  openrouter_dynamic_metadata: '根据 OpenRouter 模型元数据提供推理控制',
  xai_grok_43: '支持官方推理强度控制的 xAI Grok 模型',
  groq_qwen_reasoning: '支持默认或关闭推理的 Groq Qwen 模型',
  groq_gpt_oss: '支持低、中、高推理强度的 Groq GPT-OSS 模型',
  ollama_local_reasoning_metadata: '支持动态思考的本地 Ollama 模型系列',
};

const ZH_TW_MODEL_NOTES: Readonly<Record<FlowerProviderModelNoteKey, string>> = {
  openai_gpt_55_frontier: '適合複雜推理和程式碼任務的最新前沿模型',
  openai_gpt_54_professional: '適合專業工作的高性價比前沿模型',
  openai_gpt_54_mini: '快速且成本友善的 GPT-5.4 變體',
  openai_gpt_54_nano: '適合簡單高頻任務的低成本選項',
  openai_gpt_52_previous_flagship: '上一代旗艦模型',
  openai_gpt_52_mini: '高性價比旗艦變體',
  openai_gpt_5_stable: '穩定版旗艦模型',
  openai_gpt_5_mini: '穩定輕量選項',
  claude_opus_47_note: '適合複雜自主程式設計任務的最強 Claude 模型',
  anthropic_sonnet_46: '速度與智慧平衡最佳',
  claude_haiku_45_note: '目前最快的 Claude 模型',
  moonshot_kimi_k26: '內建網頁搜尋的目前 Kimi 旗艦模型',
  chatglm_glm_51: '內建網頁搜尋的目前 GLM 旗艦模型',
  deepseek_v4_pro: '目前 V4 旗艦模型',
  deepseek_v4_flash: '目前 V4 快速模型',
  qwen36_plus: '內建網頁搜尋的目前 Qwen3.6 Plus',
  qwen36_plus_snapshot: '內建網頁搜尋的 Qwen3.6 Plus 固定快照',
  qwen36_flash: '內建網頁搜尋的目前 Qwen3.6 Flash',
  qwen36_flash_snapshot: '內建網頁搜尋的 Qwen3.6 Flash 固定快照',
  openrouter_dynamic_metadata: '依據 OpenRouter 模型中繼資料提供推理控制',
  xai_grok_43: '支援官方推理強度控制的 xAI Grok 模型',
  groq_qwen_reasoning: '支援預設或關閉推理的 Groq Qwen 模型',
  groq_gpt_oss: '支援低、中、高推理強度的 Groq GPT-OSS 模型',
  ollama_local_reasoning_metadata: '支援動態思考的本機 Ollama 模型系列',
};

const JA_JP_MODEL_NOTES: Readonly<Record<FlowerProviderModelNoteKey, string>> = {
  openai_gpt_55_frontier: '複雑な推論とコーディングに適した最新のフロンティアモデル',
  openai_gpt_54_professional: '専門的な作業向けの手頃なフロンティアモデル',
  openai_gpt_54_mini: '高速で費用対効果に優れた GPT-5.4 の派生モデル',
  openai_gpt_54_nano: '単純で大量のタスクに適した低コストモデル',
  openai_gpt_52_previous_flagship: '前世代のフラッグシップモデル',
  openai_gpt_52_mini: '費用対効果に優れたフラッグシップ派生モデル',
  openai_gpt_5_stable: '安定版のフラッグシップモデル',
  openai_gpt_5_mini: '安定版の軽量モデル',
  claude_opus_47_note: '複雑な自律型コーディングに最も適した Claude モデル',
  anthropic_sonnet_46: '速度と知能のバランスに優れたモデル',
  claude_haiku_45_note: '現在最速の Claude モデル',
  moonshot_kimi_k26: 'ウェブ検索を内蔵した現行 Kimi フラッグシップ',
  chatglm_glm_51: 'ウェブ検索を内蔵した現行 GLM フラッグシップ',
  deepseek_v4_pro: '現行 V4 フラッグシップモデル',
  deepseek_v4_flash: '現行 V4 高速モデル',
  qwen36_plus: 'ウェブ検索を内蔵した現行 Qwen3.6 Plus',
  qwen36_plus_snapshot: 'ウェブ検索を内蔵した固定版 Qwen3.6 Plus',
  qwen36_flash: 'ウェブ検索を内蔵した現行 Qwen3.6 Flash',
  qwen36_flash_snapshot: 'ウェブ検索を内蔵した固定版 Qwen3.6 Flash',
  openrouter_dynamic_metadata: 'OpenRouter のモデルメタデータに基づく推論制御',
  xai_grok_43: '公式の推論強度制御に対応した xAI Grok モデル',
  groq_qwen_reasoning: '推論の既定値と無効化に対応した Groq Qwen モデル',
  groq_gpt_oss: '低・中・高の推論強度に対応した Groq GPT-OSS モデル',
  ollama_local_reasoning_metadata: '動的思考に対応したローカル Ollama モデル群',
};

const KO_KR_MODEL_NOTES: Readonly<Record<FlowerProviderModelNoteKey, string>> = {
  openai_gpt_55_frontier: '복잡한 추론과 코딩에 적합한 최신 프런티어 모델',
  openai_gpt_54_professional: '전문 작업을 위한 경제적인 프런티어 모델',
  openai_gpt_54_mini: '빠르고 비용 효율적인 GPT-5.4 변형 모델',
  openai_gpt_54_nano: '단순한 대량 작업을 위한 저비용 모델',
  openai_gpt_52_previous_flagship: '이전 세대 플래그십 모델',
  openai_gpt_52_mini: '비용 효율적인 플래그십 변형 모델',
  openai_gpt_5_stable: '안정적인 플래그십 모델',
  openai_gpt_5_mini: '안정적인 경량 모델',
  claude_opus_47_note: '복잡한 자율 코딩에 가장 적합한 Claude 모델',
  anthropic_sonnet_46: '속도와 지능의 균형이 가장 좋은 모델',
  claude_haiku_45_note: '현재 가장 빠른 Claude 모델',
  moonshot_kimi_k26: '웹 검색이 내장된 현재 Kimi 플래그십',
  chatglm_glm_51: '웹 검색이 내장된 현재 GLM 플래그십',
  deepseek_v4_pro: '현재 V4 플래그십 모델',
  deepseek_v4_flash: '현재 V4 고속 모델',
  qwen36_plus: '웹 검색이 내장된 현재 Qwen3.6 Plus',
  qwen36_plus_snapshot: '웹 검색이 내장된 고정 Qwen3.6 Plus 스냅샷',
  qwen36_flash: '웹 검색이 내장된 현재 Qwen3.6 Flash',
  qwen36_flash_snapshot: '웹 검색이 내장된 고정 Qwen3.6 Flash 스냅샷',
  openrouter_dynamic_metadata: 'OpenRouter 모델 메타데이터에 따른 추론 제어',
  xai_grok_43: '공식 추론 강도 제어를 지원하는 xAI Grok 모델',
  groq_qwen_reasoning: '기본 추론과 추론 끄기를 지원하는 Groq Qwen 모델',
  groq_gpt_oss: '낮음, 중간, 높음 추론 강도를 지원하는 Groq GPT-OSS 모델',
  ollama_local_reasoning_metadata: '동적 사고를 지원하는 로컬 Ollama 모델군',
};

const DE_DE_MODEL_NOTES: Readonly<Record<FlowerProviderModelNoteKey, string>> = {
  openai_gpt_55_frontier: 'Neuestes Frontier-Modell für komplexes Schlussfolgern und Programmieren',
  openai_gpt_54_professional: 'Preiswertes Frontier-Modell für professionelle Aufgaben',
  openai_gpt_54_mini: 'Schnelle und kosteneffiziente GPT-5.4-Variante',
  openai_gpt_54_nano: 'Kostengünstige Option für einfache Aufgaben mit hohem Volumen',
  openai_gpt_52_previous_flagship: 'Vorheriges Spitzenmodell',
  openai_gpt_52_mini: 'Kosteneffiziente Variante des Spitzenmodells',
  openai_gpt_5_stable: 'Stabiles Spitzenmodell',
  openai_gpt_5_mini: 'Stabile, leichtgewichtige Option',
  claude_opus_47_note: 'Leistungsfähigstes Claude-Modell für komplexe autonome Programmieraufgaben',
  anthropic_sonnet_46: 'Bestes Verhältnis von Geschwindigkeit und Leistungsfähigkeit',
  claude_haiku_45_note: 'Derzeit schnellstes Claude-Modell',
  moonshot_kimi_k26: 'Aktuelles Kimi-Spitzenmodell mit integrierter Websuche',
  chatglm_glm_51: 'Aktuelles GLM-Spitzenmodell mit integrierter Websuche',
  deepseek_v4_pro: 'Aktuelles V4-Spitzenmodell',
  deepseek_v4_flash: 'Aktuelles schnelles V4-Modell',
  qwen36_plus: 'Aktuelles Qwen3.6 Plus mit integrierter Websuche',
  qwen36_plus_snapshot: 'Fixierter Qwen3.6-Plus-Snapshot mit integrierter Websuche',
  qwen36_flash: 'Aktuelles Qwen3.6 Flash mit integrierter Websuche',
  qwen36_flash_snapshot: 'Fixierter Qwen3.6-Flash-Snapshot mit integrierter Websuche',
  openrouter_dynamic_metadata: 'Steuerung der Schlussfolgerung anhand der OpenRouter-Modellmetadaten',
  xai_grok_43: 'xAI-Grok-Modell mit offizieller Steuerung der Schlussfolgerungsintensität',
  groq_qwen_reasoning: 'Groq-Qwen-Modell mit standardmäßigem oder deaktiviertem Schlussfolgern',
  groq_gpt_oss: 'Groq-GPT-OSS-Modell mit niedriger, mittlerer und hoher Schlussfolgerungsintensität',
  ollama_local_reasoning_metadata: 'Lokale Ollama-Modellfamilie mit dynamischer Denkunterstützung',
};

const FR_FR_MODEL_NOTES: Readonly<Record<FlowerProviderModelNoteKey, string>> = {
  openai_gpt_55_frontier: 'Dernier modèle de pointe pour le raisonnement complexe et le code',
  openai_gpt_54_professional: 'Modèle de pointe abordable pour les tâches professionnelles',
  openai_gpt_54_mini: 'Variante GPT-5.4 rapide et économique',
  openai_gpt_54_nano: 'Option économique pour les tâches simples à grand volume',
  openai_gpt_52_previous_flagship: 'Ancien modèle phare',
  openai_gpt_52_mini: 'Variante économique du modèle phare',
  openai_gpt_5_stable: 'Modèle phare stable',
  openai_gpt_5_mini: 'Option légère et stable',
  claude_opus_47_note: 'Modèle Claude le plus performant pour le développement autonome complexe',
  anthropic_sonnet_46: 'Meilleur équilibre entre vitesse et intelligence',
  claude_haiku_45_note: 'Modèle Claude actuel le plus rapide',
  moonshot_kimi_k26: 'Modèle phare Kimi actuel avec recherche web intégrée',
  chatglm_glm_51: 'Modèle phare GLM actuel avec recherche web intégrée',
  deepseek_v4_pro: 'Modèle phare V4 actuel',
  deepseek_v4_flash: 'Modèle V4 rapide actuel',
  qwen36_plus: 'Qwen3.6 Plus actuel avec recherche web intégrée',
  qwen36_plus_snapshot: 'Instantané Qwen3.6 Plus figé avec recherche web intégrée',
  qwen36_flash: 'Qwen3.6 Flash actuel avec recherche web intégrée',
  qwen36_flash_snapshot: 'Instantané Qwen3.6 Flash figé avec recherche web intégrée',
  openrouter_dynamic_metadata: 'Contrôle du raisonnement à partir des métadonnées de modèle OpenRouter',
  xai_grok_43: 'Modèle xAI Grok avec contrôle officiel de l’intensité du raisonnement',
  groq_qwen_reasoning: 'Modèle Groq Qwen avec raisonnement par défaut ou désactivé',
  groq_gpt_oss: 'Modèle Groq GPT-OSS avec raisonnement faible, moyen ou élevé',
  ollama_local_reasoning_metadata: 'Famille de modèles Ollama locaux avec réflexion dynamique',
};

const ES_ES_MODEL_NOTES: Readonly<Record<FlowerProviderModelNoteKey, string>> = {
  openai_gpt_55_frontier: 'Último modelo de vanguardia para razonamiento complejo y programación',
  openai_gpt_54_professional: 'Modelo de vanguardia asequible para trabajo profesional',
  openai_gpt_54_mini: 'Variante de GPT-5.4 rápida y rentable',
  openai_gpt_54_nano: 'Opción económica para tareas sencillas de gran volumen',
  openai_gpt_52_previous_flagship: 'Modelo insignia anterior',
  openai_gpt_52_mini: 'Variante rentable del modelo insignia',
  openai_gpt_5_stable: 'Modelo insignia estable',
  openai_gpt_5_mini: 'Opción ligera y estable',
  claude_opus_47_note: 'Modelo Claude más capaz para programación autónoma compleja',
  anthropic_sonnet_46: 'Mejor equilibrio entre velocidad e inteligencia',
  claude_haiku_45_note: 'Modelo Claude actual más rápido',
  moonshot_kimi_k26: 'Modelo insignia actual de Kimi con búsqueda web integrada',
  chatglm_glm_51: 'Modelo insignia actual de GLM con búsqueda web integrada',
  deepseek_v4_pro: 'Modelo insignia V4 actual',
  deepseek_v4_flash: 'Modelo V4 rápido actual',
  qwen36_plus: 'Qwen3.6 Plus actual con búsqueda web integrada',
  qwen36_plus_snapshot: 'Instantánea fija de Qwen3.6 Plus con búsqueda web integrada',
  qwen36_flash: 'Qwen3.6 Flash actual con búsqueda web integrada',
  qwen36_flash_snapshot: 'Instantánea fija de Qwen3.6 Flash con búsqueda web integrada',
  openrouter_dynamic_metadata: 'Controles de razonamiento basados en los metadatos de modelos de OpenRouter',
  xai_grok_43: 'Modelo xAI Grok con control oficial de la intensidad de razonamiento',
  groq_qwen_reasoning: 'Modelo Groq Qwen con razonamiento predeterminado o desactivado',
  groq_gpt_oss: 'Modelo Groq GPT-OSS con razonamiento bajo, medio y alto',
  ollama_local_reasoning_metadata: 'Familia de modelos Ollama locales con pensamiento dinámico',
};

const PT_BR_MODEL_NOTES: Readonly<Record<FlowerProviderModelNoteKey, string>> = {
  openai_gpt_55_frontier: 'Modelo de ponta mais recente para raciocínio complexo e programação',
  openai_gpt_54_professional: 'Modelo de ponta acessível para trabalho profissional',
  openai_gpt_54_mini: 'Variante do GPT-5.4 rápida e econômica',
  openai_gpt_54_nano: 'Opção de baixo custo para tarefas simples em grande volume',
  openai_gpt_52_previous_flagship: 'Modelo principal anterior',
  openai_gpt_52_mini: 'Variante econômica do modelo principal',
  openai_gpt_5_stable: 'Modelo principal estável',
  openai_gpt_5_mini: 'Opção leve e estável',
  claude_opus_47_note: 'Modelo Claude mais capaz para programação autônoma complexa',
  anthropic_sonnet_46: 'Melhor equilíbrio entre velocidade e inteligência',
  claude_haiku_45_note: 'Modelo Claude atual mais rápido',
  moonshot_kimi_k26: 'Modelo principal atual do Kimi com pesquisa na web integrada',
  chatglm_glm_51: 'Modelo principal atual do GLM com pesquisa na web integrada',
  deepseek_v4_pro: 'Modelo principal V4 atual',
  deepseek_v4_flash: 'Modelo V4 rápido atual',
  qwen36_plus: 'Qwen3.6 Plus atual com pesquisa na web integrada',
  qwen36_plus_snapshot: 'Snapshot fixo do Qwen3.6 Plus com pesquisa na web integrada',
  qwen36_flash: 'Qwen3.6 Flash atual com pesquisa na web integrada',
  qwen36_flash_snapshot: 'Snapshot fixo do Qwen3.6 Flash com pesquisa na web integrada',
  openrouter_dynamic_metadata: 'Controles de raciocínio baseados nos metadados de modelos do OpenRouter',
  xai_grok_43: 'Modelo xAI Grok com controle oficial da intensidade de raciocínio',
  groq_qwen_reasoning: 'Modelo Groq Qwen com raciocínio padrão ou desativado',
  groq_gpt_oss: 'Modelo Groq GPT-OSS com raciocínio baixo, médio e alto',
  ollama_local_reasoning_metadata: 'Família de modelos Ollama locais com pensamento dinâmico',
};

const RU_RU_MODEL_NOTES: Readonly<Record<FlowerProviderModelNoteKey, string>> = {
  openai_gpt_55_frontier: 'Новейшая передовая модель для сложных рассуждений и программирования',
  openai_gpt_54_professional: 'Доступная передовая модель для профессиональных задач',
  openai_gpt_54_mini: 'Быстрый и экономичный вариант GPT-5.4',
  openai_gpt_54_nano: 'Недорогой вариант для простых массовых задач',
  openai_gpt_52_previous_flagship: 'Предыдущая флагманская модель',
  openai_gpt_52_mini: 'Экономичный вариант флагманской модели',
  openai_gpt_5_stable: 'Стабильная флагманская модель',
  openai_gpt_5_mini: 'Стабильный облегчённый вариант',
  claude_opus_47_note: 'Самая мощная модель Claude для сложного автономного программирования',
  anthropic_sonnet_46: 'Лучший баланс скорости и интеллекта',
  claude_haiku_45_note: 'Самая быстрая текущая модель Claude',
  moonshot_kimi_k26: 'Текущая флагманская модель Kimi со встроенным веб-поиском',
  chatglm_glm_51: 'Текущая флагманская модель GLM со встроенным веб-поиском',
  deepseek_v4_pro: 'Текущая флагманская модель V4',
  deepseek_v4_flash: 'Текущая быстрая модель V4',
  qwen36_plus: 'Текущая Qwen3.6 Plus со встроенным веб-поиском',
  qwen36_plus_snapshot: 'Зафиксированная версия Qwen3.6 Plus со встроенным веб-поиском',
  qwen36_flash: 'Текущая Qwen3.6 Flash со встроенным веб-поиском',
  qwen36_flash_snapshot: 'Зафиксированная версия Qwen3.6 Flash со встроенным веб-поиском',
  openrouter_dynamic_metadata: 'Управление рассуждением на основе метаданных моделей OpenRouter',
  xai_grok_43: 'Модель xAI Grok с официальным управлением интенсивностью рассуждения',
  groq_qwen_reasoning: 'Модель Groq Qwen с рассуждением по умолчанию или без него',
  groq_gpt_oss: 'Модель Groq GPT-OSS с низкой, средней и высокой интенсивностью рассуждения',
  ollama_local_reasoning_metadata: 'Семейство локальных моделей Ollama с динамическим мышлением',
};

function modelNotesForLocale(locale: string | undefined): Readonly<Record<FlowerProviderModelNoteKey, string>> {
  const normalized = String(locale ?? '').toLowerCase();
  if (normalized.startsWith('zh-tw') || normalized.startsWith('zh-hant') || normalized.startsWith('zh-hk')) return ZH_TW_MODEL_NOTES;
  if (normalized.startsWith('zh')) return ZH_CN_MODEL_NOTES;
  if (normalized.startsWith('ja')) return JA_JP_MODEL_NOTES;
  if (normalized.startsWith('ko')) return KO_KR_MODEL_NOTES;
  if (normalized.startsWith('de')) return DE_DE_MODEL_NOTES;
  if (normalized.startsWith('fr')) return FR_FR_MODEL_NOTES;
  if (normalized.startsWith('es')) return ES_ES_MODEL_NOTES;
  if (normalized.startsWith('pt')) return PT_BR_MODEL_NOTES;
  if (normalized.startsWith('ru')) return RU_RU_MODEL_NOTES;
  return EN_US_MODEL_NOTES;
}

export function localizedFlowerProviderModelNote(
  locale: string | undefined,
  noteKey: FlowerProviderModelNoteKey | undefined,
): string {
  if (!noteKey) return '';
  return modelNotesForLocale(locale)[noteKey] ?? EN_US_MODEL_NOTES[noteKey] ?? '';
}
