// Generated by ReDevPlugin. Do not edit.
import {
  callCapabilityOperation,
  callCapabilityStream,
  callCapabilitySync,
  isCapabilityBusinessError,
  type PluginBridgeClient,
  type PluginBridgeError,
  type PluginBridgeRequestOptions,
  type PluginOperation,
  type PluginStream,
} from "@floegence/redevplugin-ui/plugin";

export type ContainersStatusRequest = {
  engine: "docker" | "podman";
};

export type ContainersStatusResponse = {
  available: boolean;
  engine: "docker" | "podman";
  engine_version?: string;
};

export type ContainersListRequest = {
  all?: boolean;
  engine: "docker" | "podman";
};

export type ContainersListResponse = {
  containers: Array<{
    container_id: string;
    created_at_unix_ms?: number;
    image: {
      digest?: string;
      digest_pinned: boolean;
      reference?: string;
    };
    name?: string;
    ports?: Array<{
      host_ip?: string;
      host_port?: number;
      port: number;
      protocol?: string;
    }>;
    state: "created" | "running" | "paused" | "restarting" | "exited" | "stopped" | "unknown";
  }>;
  engine: "docker" | "podman";
};

export type ContainersInspectRequest = {
  container_id: string;
  engine: "docker" | "podman";
};

export type ContainersInspectResponse = {
  container: {
    container_id: string;
    created_at_unix_ms?: number;
    image: {
      digest?: string;
      digest_pinned: boolean;
      reference?: string;
    };
    name?: string;
    ports?: Array<{
      host_ip?: string;
      host_port?: number;
      port: number;
      protocol?: string;
    }>;
    state: "created" | "running" | "paused" | "restarting" | "exited" | "stopped" | "unknown";
  };
  engine: "docker" | "podman";
};

export type ContainersStartPreflightRequest = {
  container_id: string;
  engine: "docker" | "podman";
};

export type ContainersStartPreflightResponse = {
  image: {
    digest?: string;
    digest_pinned: boolean;
    reference?: string;
  };
  method: "containers.start";
  request: {
    container_id: string;
    engine: "docker" | "podman";
  };
  requires_admin: boolean;
  risk_flags: Array<{
    admin_required?: boolean;
    detail?: string;
    id: string;
    severity: "low" | "medium" | "high" | "critical";
    title: string;
  }>;
  risk_level: "none" | "low" | "medium" | "high" | "critical";
  runtime: {
    ipc_mode?: string;
    network_mode?: string;
    pid_mode?: string;
    privileged: boolean;
    restart_policy?: string;
  };
  summary?: Array<string>;
  target: {
    container_id: string;
    container_name?: string;
    engine: "docker" | "podman";
    target_hash: string;
  };
};

export type ContainersStartRequest = {
  container_id: string;
  engine: "docker" | "podman";
};

export type ContainersStartResponse = {
  accepted: boolean;
  container_id: string;
  engine: "docker" | "podman";
  method: "containers.start";
};

export type ContainersStopRequest = {
  container_id: string;
  engine: "docker" | "podman";
  timeout_sec?: number;
};

export type ContainersStopResponse = {
  accepted: boolean;
  container_id: string;
  engine: "docker" | "podman";
  method: "containers.stop";
};

export type ContainersRestartRequest = {
  container_id: string;
  engine: "docker" | "podman";
  timeout_sec?: number;
};

export type ContainersRestartResponse = {
  accepted: boolean;
  container_id: string;
  engine: "docker" | "podman";
  method: "containers.restart";
};

export type ContainersRemoveRequest = {
  container_id: string;
  engine: "docker" | "podman";
  force?: boolean;
};

export type ContainersRemoveResponse = {
  accepted: boolean;
  container_id: string;
  engine: "docker" | "podman";
  method: "containers.remove";
};

export type ContainersTailLogsRequest = {
  container_id: string;
  engine: "docker" | "podman";
  follow?: boolean;
  since_unix_ms?: number;
  tail_lines?: number;
};

export type ContainersTailLogsResponse = {
  container_id: string;
  engine: "docker" | "podman";
  subscribed: boolean;
};

export type ContainerLogEvent = {
  message: string;
  timestamp_unix_ms?: number;
};

export type ImagesPullRequest = {
  engine: "docker" | "podman";
  image_ref: string;
};

export type ImagesPullResponse = {
  accepted: boolean;
  engine: "docker" | "podman";
  image_ref: string;
};

export type RedevenContainerResourcesBusinessErrorCode = "CONTAINER_ENGINE_UNAVAILABLE" | "CONTAINER_LOGS_UNAVAILABLE" | "CONTAINER_NOT_FOUND" | "CONTAINER_OPERATION_FAILED";

export type RedevenContainerResourcesBusinessErrorDetails =
  | {
    capability_id: "redeven.capability.container_resources";
    capability_version: "1.0.0";
    detail_schema_sha256: "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b";
    business_error_code: "CONTAINER_ENGINE_UNAVAILABLE";
  }
  | {
    capability_id: "redeven.capability.container_resources";
    capability_version: "1.0.0";
    detail_schema_sha256: "be82c653c55a1c2fc0189b74e5a84591982273a37a5a7d26b64f0b6b7441386f";
    business_error_code: "CONTAINER_NOT_FOUND";
    business_error_details: {
      container_id: string;
    };
  }
  | {
    capability_id: "redeven.capability.container_resources";
    capability_version: "1.0.0";
    detail_schema_sha256: "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b";
    business_error_code: "CONTAINER_OPERATION_FAILED";
  }
  | {
    capability_id: "redeven.capability.container_resources";
    capability_version: "1.0.0";
    detail_schema_sha256: "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b";
    business_error_code: "CONTAINER_LOGS_UNAVAILABLE";
  };

export function isRedevenContainerResourcesBusinessError(error: unknown): error is PluginBridgeError & { readonly details: RedevenContainerResourcesBusinessErrorDetails } {
  return isCapabilityBusinessError(error, "redeven.capability.container_resources", "1.0.0", {
    "CONTAINER_ENGINE_UNAVAILABLE": { detail_schema_sha256: "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b", schema: null },
    "CONTAINER_NOT_FOUND": { detail_schema_sha256: "be82c653c55a1c2fc0189b74e5a84591982273a37a5a7d26b64f0b6b7441386f", schema: {"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"}},"required":["container_id"],"type":"object"} },
    "CONTAINER_OPERATION_FAILED": { detail_schema_sha256: "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b", schema: null },
    "CONTAINER_LOGS_UNAVAILABLE": { detail_schema_sha256: "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b", schema: null },
  });
}

const statusContract = Object.freeze({
  method: "containers.status",
  effect: "read",
  execution: "sync",
  requestSchema: {"additionalProperties":false,"properties":{"engine":{"enum":["docker","podman"],"type":"string"}},"required":["engine"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"available":{"type":"boolean"},"engine":{"enum":["docker","podman"],"type":"string"},"engine_version":{"type":"string"}},"required":["engine","available"],"type":"object"},
} as const);

const listContract = Object.freeze({
  method: "containers.list",
  effect: "read",
  execution: "sync",
  requestSchema: {"additionalProperties":false,"properties":{"all":{"type":"boolean"},"engine":{"enum":["docker","podman"],"type":"string"}},"required":["engine"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"containers":{"items":{"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"created_at_unix_ms":{"minimum":0,"type":"integer"},"image":{"additionalProperties":false,"properties":{"digest":{"type":"string"},"digest_pinned":{"type":"boolean"},"reference":{"type":"string"}},"required":["digest_pinned"],"type":"object"},"name":{"type":"string"},"ports":{"items":{"additionalProperties":false,"properties":{"host_ip":{"type":"string"},"host_port":{"minimum":0,"type":"integer"},"port":{"maximum":65535,"minimum":1,"type":"integer"},"protocol":{"type":"string"}},"required":["port"],"type":"object"},"type":"array"},"state":{"enum":["created","running","paused","restarting","exited","stopped","unknown"],"type":"string"}},"required":["container_id","image","state"],"type":"object"},"type":"array"},"engine":{"enum":["docker","podman"],"type":"string"}},"required":["engine","containers"],"type":"object"},
} as const);

const inspectContract = Object.freeze({
  method: "containers.inspect",
  effect: "read",
  execution: "sync",
  requestSchema: {"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"}},"required":["engine","container_id"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"container":{"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"created_at_unix_ms":{"minimum":0,"type":"integer"},"image":{"additionalProperties":false,"properties":{"digest":{"type":"string"},"digest_pinned":{"type":"boolean"},"reference":{"type":"string"}},"required":["digest_pinned"],"type":"object"},"name":{"type":"string"},"ports":{"items":{"additionalProperties":false,"properties":{"host_ip":{"type":"string"},"host_port":{"minimum":0,"type":"integer"},"port":{"maximum":65535,"minimum":1,"type":"integer"},"protocol":{"type":"string"}},"required":["port"],"type":"object"},"type":"array"},"state":{"enum":["created","running","paused","restarting","exited","stopped","unknown"],"type":"string"}},"required":["container_id","image","state"],"type":"object"},"engine":{"enum":["docker","podman"],"type":"string"}},"required":["engine","container"],"type":"object"},
} as const);

const startPreflightContract = Object.freeze({
  method: "containers.start.preflight",
  effect: "read",
  execution: "sync",
  requestSchema: {"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"}},"required":["engine","container_id"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"image":{"additionalProperties":false,"properties":{"digest":{"type":"string"},"digest_pinned":{"type":"boolean"},"reference":{"type":"string"}},"required":["digest_pinned"],"type":"object"},"method":{"const":"containers.start","type":"string"},"request":{"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"}},"required":["engine","container_id"],"type":"object"},"requires_admin":{"type":"boolean"},"risk_flags":{"items":{"additionalProperties":false,"properties":{"admin_required":{"type":"boolean"},"detail":{"type":"string"},"id":{"minLength":1,"type":"string"},"severity":{"enum":["low","medium","high","critical"],"type":"string"},"title":{"minLength":1,"type":"string"}},"required":["id","severity","title"],"type":"object"},"type":"array"},"risk_level":{"enum":["none","low","medium","high","critical"],"type":"string"},"runtime":{"additionalProperties":false,"properties":{"ipc_mode":{"type":"string"},"network_mode":{"type":"string"},"pid_mode":{"type":"string"},"privileged":{"type":"boolean"},"restart_policy":{"type":"string"}},"required":["privileged"],"type":"object"},"summary":{"items":{"type":"string"},"type":"array"},"target":{"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"container_name":{"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"},"target_hash":{"minLength":1,"type":"string"}},"required":["engine","container_id","target_hash"],"type":"object"}},"required":["method","request","target","image","runtime","risk_level","risk_flags","requires_admin"],"type":"object"},
} as const);

const startContract = Object.freeze({
  method: "containers.start",
  effect: "execute",
  execution: "operation",
  requestSchema: {"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"}},"required":["engine","container_id"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"accepted":{"type":"boolean"},"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"},"method":{"const":"containers.start","type":"string"}},"required":["accepted","engine","container_id","method"],"type":"object"},
  cancelable: true,
} as const);

const stopContract = Object.freeze({
  method: "containers.stop",
  effect: "execute",
  execution: "operation",
  requestSchema: {"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"},"timeout_sec":{"minimum":0,"type":"integer"}},"required":["engine","container_id"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"accepted":{"type":"boolean"},"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"},"method":{"const":"containers.stop","type":"string"}},"required":["accepted","engine","container_id","method"],"type":"object"},
  cancelable: true,
} as const);

const restartContract = Object.freeze({
  method: "containers.restart",
  effect: "execute",
  execution: "operation",
  requestSchema: {"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"},"timeout_sec":{"minimum":0,"type":"integer"}},"required":["engine","container_id"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"accepted":{"type":"boolean"},"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"},"method":{"const":"containers.restart","type":"string"}},"required":["accepted","engine","container_id","method"],"type":"object"},
  cancelable: true,
} as const);

const removeContract = Object.freeze({
  method: "containers.remove",
  effect: "delete",
  execution: "operation",
  requestSchema: {"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"},"force":{"type":"boolean"}},"required":["engine","container_id"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"accepted":{"type":"boolean"},"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"},"method":{"const":"containers.remove","type":"string"}},"required":["accepted","engine","container_id","method"],"type":"object"},
  cancelable: true,
} as const);

const tailLogsContract = Object.freeze({
  method: "containers.logs.tail",
  effect: "read",
  execution: "subscription",
  requestSchema: {"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"},"follow":{"type":"boolean"},"since_unix_ms":{"minimum":0,"type":"integer"},"tail_lines":{"maximum":1000,"minimum":0,"type":"integer"}},"required":["engine","container_id"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"container_id":{"minLength":1,"type":"string"},"engine":{"enum":["docker","podman"],"type":"string"},"subscribed":{"type":"boolean"}},"required":["engine","container_id","subscribed"],"type":"object"},
  eventTypeName: "ContainerLogEvent",
  eventSchema: {"additionalProperties":false,"properties":{"message":{"type":"string"},"timestamp_unix_ms":{"minimum":0,"type":"integer"}},"required":["message"],"type":"object"},
} as const);

const pullImageContract = Object.freeze({
  method: "images.pull",
  effect: "write",
  execution: "operation",
  requestSchema: {"additionalProperties":false,"properties":{"engine":{"enum":["docker","podman"],"type":"string"},"image_ref":{"minLength":1,"type":"string"}},"required":["engine","image_ref"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"accepted":{"type":"boolean"},"engine":{"enum":["docker","podman"],"type":"string"},"image_ref":{"minLength":1,"type":"string"}},"required":["accepted","engine","image_ref"],"type":"object"},
  cancelable: true,
} as const);

export class RedevenContainerResourcesClient {
  readonly #bridge: PluginBridgeClient;

  constructor(bridge: PluginBridgeClient) {
    this.#bridge = bridge;
  }

  async status(request: ContainersStatusRequest, options: PluginBridgeRequestOptions = {}): Promise<ContainersStatusResponse> {
    return callCapabilitySync<ContainersStatusRequest, ContainersStatusResponse>(
      this.#bridge,
      statusContract,
      request,
      options,
    );
  }

  async list(request: ContainersListRequest, options: PluginBridgeRequestOptions = {}): Promise<ContainersListResponse> {
    return callCapabilitySync<ContainersListRequest, ContainersListResponse>(
      this.#bridge,
      listContract,
      request,
      options,
    );
  }

  async inspect(request: ContainersInspectRequest, options: PluginBridgeRequestOptions = {}): Promise<ContainersInspectResponse> {
    return callCapabilitySync<ContainersInspectRequest, ContainersInspectResponse>(
      this.#bridge,
      inspectContract,
      request,
      options,
    );
  }

  async startPreflight(request: ContainersStartPreflightRequest, options: PluginBridgeRequestOptions = {}): Promise<ContainersStartPreflightResponse> {
    return callCapabilitySync<ContainersStartPreflightRequest, ContainersStartPreflightResponse>(
      this.#bridge,
      startPreflightContract,
      request,
      options,
    );
  }

  async start(request: ContainersStartRequest, options: PluginBridgeRequestOptions = {}): Promise<PluginOperation<ContainersStartResponse>> {
    return callCapabilityOperation<ContainersStartRequest, ContainersStartResponse>(
      this.#bridge,
      startContract,
      request,
      options,
    );
  }

  async stop(request: ContainersStopRequest, options: PluginBridgeRequestOptions = {}): Promise<PluginOperation<ContainersStopResponse>> {
    return callCapabilityOperation<ContainersStopRequest, ContainersStopResponse>(
      this.#bridge,
      stopContract,
      request,
      options,
    );
  }

  async restart(request: ContainersRestartRequest, options: PluginBridgeRequestOptions = {}): Promise<PluginOperation<ContainersRestartResponse>> {
    return callCapabilityOperation<ContainersRestartRequest, ContainersRestartResponse>(
      this.#bridge,
      restartContract,
      request,
      options,
    );
  }

  async remove(request: ContainersRemoveRequest, options: PluginBridgeRequestOptions = {}): Promise<PluginOperation<ContainersRemoveResponse>> {
    return callCapabilityOperation<ContainersRemoveRequest, ContainersRemoveResponse>(
      this.#bridge,
      removeContract,
      request,
      options,
    );
  }

  async tailLogs(request: ContainersTailLogsRequest, options: PluginBridgeRequestOptions = {}): Promise<PluginStream<ContainersTailLogsResponse, ContainerLogEvent>> {
    return callCapabilityStream<ContainersTailLogsRequest, ContainersTailLogsResponse, ContainerLogEvent>(
      this.#bridge,
      tailLogsContract,
      request,
      options,
    );
  }

  async pullImage(request: ImagesPullRequest, options: PluginBridgeRequestOptions = {}): Promise<PluginOperation<ImagesPullResponse>> {
    return callCapabilityOperation<ImagesPullRequest, ImagesPullResponse>(
      this.#bridge,
      pullImageContract,
      request,
      options,
    );
  }

}
