#!/usr/bin/env bash
set -euo pipefail

MARKER_BASENAME=".redevplugin-release-artifacts-verified.json"

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/check_redevplugin_consumption_gate.sh --scan-root <dir> [--scan-root <dir> ...]
  ./scripts/check_redevplugin_consumption_gate.sh --self-test

Fails if a Redeven release staging directory or Desktop bundle contains
ReDevPlugin runtime payloads without a verifier marker generated by
check_redevplugin_release_artifacts.sh --write-marker.
USAGE
}

scan_roots=()
self_test=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --scan-root)
      if [[ $# -lt 2 ]]; then
        echo "--scan-root requires a directory" >&2
        usage >&2
        exit 2
      fi
      scan_roots+=("$2")
      shift 2
      ;;
    --self-test)
      self_test=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unexpected argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

write_self_test_marker() {
  local marker_path="$1"
  cat >"$marker_path" <<'JSON'
{
  "schema_version": "redeven.redevplugin_artifact_verification.v1",
  "sha256sums_sha256": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "stress_summary_sha256": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  "tarballs": [
    {
      "name": "redevplugin-v0.0.0-test-linux-amd64.tar.gz",
      "sha256": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
    }
  ]
}
JSON
}

assert_scan_root() {
  local root="$1"
  local marker_path="$root/$MARKER_BASENAME"
  local payload_list

  payload_list=$(find_redevplugin_payloads "$root")
  if [[ -z "$payload_list" ]]; then
    echo "[INFO] no ReDevPlugin payloads found in ${root}"
    return 0
  fi

  if [[ ! -f "$marker_path" ]]; then
    printf '%s\n' "$payload_list" >&2
    echo "[redevplugin-consumption] ReDevPlugin payloads require verifier marker: $marker_path" >&2
    exit 1
  fi

  validate_marker "$marker_path"
  echo "[INFO] ReDevPlugin consumption marker verified for ${root}"
}

find_redevplugin_payloads() {
  local root="$1"
  local file name
  while IFS= read -r -d '' file; do
    name=$(basename -- "$file")
    case "$name" in
      "$MARKER_BASENAME")
        continue
        ;;
      redevplugin-runtime|redevplugin-runtime.exe|redevplugin-release-stress.json)
        printf '%s\n' "$file"
        continue
        ;;
    esac
    if [[ "$name" =~ ^redevplugin-.+\.tar\.gz$ ]]; then
      printf '%s\n' "$file"
      continue
    fi
    if [[ "$name" == *.tar.gz ]] && tarball_contains_redevplugin_runtime "$file"; then
      printf '%s: contains redevplugin-runtime\n' "$file"
    fi
  done < <(find "$root" -type f -print0)
}

tarball_contains_redevplugin_runtime() {
  local tarball="$1"
  tar -tzf "$tarball" 2>/dev/null | grep -Eq '(^|/)redevplugin-runtime(\.exe)?$'
}

validate_marker() {
  local marker_path="$1"
  MARKER_PATH="$marker_path" node <<'NODE'
const { readFileSync } = require("node:fs");

const markerPath = process.env.MARKER_PATH;
let marker;
try {
  marker = JSON.parse(readFileSync(markerPath, "utf8"));
} catch (error) {
  fail(`failed to parse marker JSON: ${error.message}`);
}

if (!marker || typeof marker !== "object" || Array.isArray(marker)) {
  fail("marker must be an object");
}
if (marker.schema_version !== "redeven.redevplugin_artifact_verification.v1") {
  fail("marker schema_version mismatch");
}
for (const field of ["sha256sums_sha256", "stress_summary_sha256"]) {
  assertHash(marker[field], field);
}
if (!Array.isArray(marker.tarballs) || marker.tarballs.length === 0) {
  fail("marker tarballs must be a non-empty array");
}
for (const [index, tarball] of marker.tarballs.entries()) {
  if (!tarball || typeof tarball !== "object" || Array.isArray(tarball)) {
    fail(`marker tarballs[${index}] must be an object`);
  }
  if (typeof tarball.name !== "string" || !/^redevplugin-.+\.tar\.gz$/u.test(tarball.name)) {
    fail(`marker tarballs[${index}].name must be a ReDevPlugin tarball name`);
  }
  assertHash(tarball.sha256, `tarballs[${index}].sha256`);
}

function assertHash(value, label) {
  if (typeof value !== "string" || !/^[0-9a-f]{64}$/u.test(value)) {
    fail(`${label} must be lowercase SHA-256 hex`);
  }
}

function fail(message) {
  console.error(`[redevplugin-consumption] ${message}`);
  process.exit(1);
}
NODE
}

if [[ "$self_test" -eq 1 ]]; then
  if [[ "${#scan_roots[@]}" -gt 0 ]]; then
    echo "--self-test cannot be combined with --scan-root" >&2
    exit 2
  fi
  tmpdir=$(mktemp -d)
  trap 'rm -rf "$tmpdir"' EXIT

  clean_root="$tmpdir/clean"
  missing_marker_root="$tmpdir/missing-marker"
  invalid_marker_root="$tmpdir/invalid-marker"
  valid_marker_root="$tmpdir/valid-marker"
  tarball_root="$tmpdir/tarball"
  mkdir -p "$clean_root" "$missing_marker_root/bin" "$invalid_marker_root/bin" "$valid_marker_root/bin" "$tarball_root/payload/bin"

  printf 'redeven runtime\n' >"$clean_root/redeven"
  "$0" --scan-root "$clean_root"

  printf 'plugin runtime\n' >"$missing_marker_root/bin/redevplugin-runtime"
  if "$0" --scan-root "$missing_marker_root" >/dev/null 2>&1; then
    echo "self-test expected missing marker root to fail" >&2
    exit 1
  fi

  printf 'plugin runtime\n' >"$invalid_marker_root/bin/redevplugin-runtime"
  printf '{}\n' >"$invalid_marker_root/$MARKER_BASENAME"
  if "$0" --scan-root "$invalid_marker_root" >/dev/null 2>&1; then
    echo "self-test expected invalid marker root to fail" >&2
    exit 1
  fi

  printf 'plugin runtime\n' >"$valid_marker_root/bin/redevplugin-runtime"
  write_self_test_marker "$valid_marker_root/$MARKER_BASENAME"
  "$0" --scan-root "$valid_marker_root"

  printf 'plugin runtime\n' >"$tarball_root/payload/bin/redevplugin-runtime"
  tar -czf "$tarball_root/redeven_linux_amd64.tar.gz" -C "$tarball_root/payload" .
  rm -rf "$tarball_root/payload"
  if "$0" --scan-root "$tarball_root" >/dev/null 2>&1; then
    echo "self-test expected tarball with embedded plugin runtime to fail" >&2
    exit 1
  fi
  write_self_test_marker "$tarball_root/$MARKER_BASENAME"
  "$0" --scan-root "$tarball_root"

  exit 0
fi

if [[ "${#scan_roots[@]}" -eq 0 ]]; then
  usage >&2
  exit 2
fi

for root in "${scan_roots[@]}"; do
  if [[ ! -d "$root" ]]; then
    echo "[redevplugin-consumption] scan root not found: $root" >&2
    exit 1
  fi
  assert_scan_root "$root"
done
