import { REDEVEN_WORKBENCH_LOCAL_SCROLL_VIEWPORT_PROPS } from '../workbench/surface/workbenchWheelInteractive';

export const GIT_WORKBENCH_SCROLL_REGION_PROPS = REDEVEN_WORKBENCH_LOCAL_SCROLL_VIEWPORT_PROPS;
